### ISSUE TITLE
Environment variables no longer work

### ISSUE THREAD

**Issue by bdubn** [citrix/terraform-provider-citrixadc#100]
**Describe the bug**
What is described in the readme no longer works for handling authentication to the ADC when the password is not default on the ADC.

**To Reproduce**
Follow the readme.

provider "citrixadc" {
    username = "${var.ns_user}"
    password = "${var.ns_password}"
    endpoint = "http://10.71.136.250/"
}

In current version of terraform, it is advised to change to:

provider "citrixadc" {
    username = "var.ns_user"
    password = "var.ns_password"
    endpoint = "http://10.71.136.250/"
}

"Terraform 0.11 and earlier required all non-constant expressions to be provided via interpolation syntax, but this pattern is now deprecated. To silence this warning, remove the "${ sequence from the start and the }" sequence from the end of this expression, leaving just the inner expression."

**Expected behavior**
Expect it to work.

**Environment (please complete the following information):**
 - OS: MacOS
 - Provider version v0.12.23
 - Terraform version v0.12.24
 - Citrix ADC version v13.0.41.28

**Additional context**
I have tried many other combinations to no avail to get it to work but nothing works. If I utilize the default nsroot password on the ADC and eliminate the username and password lines from the provider block, everything works fine.

**Comment by bdubn** [comment]
I was able to resolve this with the following:

export TF_VAR_ns_user=nsroot
export TF_VAR_ns_password=<custom_password>
export TF_VAR_ns_url=http://10.71.136.250/

-------------------

variable "ns_user" {
  type = string
}

variable "ns_password" {
  type = string
}

provider "citrixadc" {
    username = var.ns_user
    password = var.ns_password
    endpoint = "http://10.71.136.250/"
}

**Comment by numard** [comment]
Hi, 
FWIW, I'm using terraform 0.12.18, latest (and many previous versions ) adx provider - 

I am not setting username nor password at all, and using env variables NS_USER and NS_PASSWORD with no issue at all.
cheers,

**Comment by vadharm** [comment]
Need triage.

**Comment by giorgos-nikolopoulos** [comment]
See [this section](https://github.com/citrix/terraform-provider-citrixadc#argument-reference) of the README for which environment variables correspond to which provider option.

The example where `var.ns_user` is used requires this variable to be set by some means. Either through a variables file or following the terraform environment variable naming convention.

Will close this since there is no issue to resolve.
