### ISSUE TITLE
When setting timeout to 0 on citrixadc_lbvserver , provider says successful but the value is set to default: 2 on netscaler

### ISSUE THREAD

**Issue by piontekdd** [citrix/terraform-provider-citrixadc#101]
**Describe the bug**
We are trying to set the timeout value to 0 (persistence never times out unless browser is closed). When running apply, the plan is applied successfully but running additional plans shows that terraform wants to change value from 2 to 0. 

**To Reproduce**
* Create a citrixadc_lbvserver resource with timeout = "0"
* Run tfm plan, tfm apply. Note the lbvserver is created successfully
* Either inspect the state or run another plan. Terraform will want to change the value from 2 -> 0
* Verify on the netscaler, the value is 2, not 0. 

**Expected behavior**
The value on the netscaler lbvserver should be set to 0.

**Logs**
From citrixadc 12.1:
this is setting it from 1440 -> 0. (existing lbvserver)
I can set it fine to 2 or any value > than that
```
2020-06-01T16:32:54.001-0500 [DEBUG] plugin.terraform-provider-citrixadc_v0.12.21: 2020/06/01 16:32:54 [DEBUG] go-nitro: response Status: 400 Bad Request
2020-06-01T16:32:54.001-0500 [DEBUG] plugin.terraform-provider-citrixadc_v0.12.21: 2020/06/01 16:32:54 [INFO] go-nitro: error = { "errorcode": 1094, "message": "Too few arguments", "severity": "ERROR" }
```

**Environment (please complete the following information):**
 - OS: MacOS Catalina, Linux
 - Provider version: v0.12.21
 - Terraform version: v0.11.10
 - Citrix ADC version: 11.1 and 12.1 (I need to verify it is repeatable in both)

**Additional context**
It is unclear to me if this is a bug in the provider, or downstream in the go-nitro library being used.

**Comment by devopsjedi** [comment]
Try running with `TF_LOG=DEBUG` and you should see the JSON payload that is used by go-nitro

**Comment by piontekdd** [comment]
Using the latest provider, I can't even get this issue to duplicate the same. Rather than it saying it changed to 0, it now just errors out:
```
2020-10-27T12:40:58.347-0500 [DEBUG] plugin.terraform-provider-citrixadc_v0.12.35: 2020/10/27 12:40:58 [DEBUG] go-nitro: response Status: 400 Bad Request
2020-10-27T12:40:58.347-0500 [DEBUG] plugin.terraform-provider-citrixadc_v0.12.35: 2020/10/27 12:40:58 [INFO] go-nitro: error = { "errorcode": 1094, "message": "Too few arguments", "severity": "ERROR" }
```

**Comment by piontekdd** [comment]
I think the issue is with the GO Nitro package being used;

https://github.com/chiradeep/go-nitro/blob/master/config/lb/lbvserver.go#L125

omitempty for JSON in GO and an int datatype will omit the value from the JSON if the value is the default for an int "0". but 0 is a valid value in the API.

**Comment by piontekdd** [comment]
This is an issue with the go-nitro api. https://github.com/chiradeep/go-nitro/issues/44

I have forked that repo and built this provider with my forked go-nitro to verify it allows us to set a value of '0'. The permanent fix, however, is a bit out of my skillset when it comes to Go .
