### ISSUE TITLE
[BUG] citrixadc_csvserver_cspolicy_binding priority is not auto incremented

### ISSUE THREAD

**Issue by srikanth2302** [citrix/terraform-provider-citrixadc#1012]
# Contact us

> For any immediate issues or help , reach out to us at appmodernization@citrix.com !

# Bug Report

**Describe the bug**
cspolicy_binding resource is not accepting priority as optional.. In Docs it says priority as optional but while executing it asks priority as mandatory field.

**To Reproduce**
Steps to reproduce the behaviour:
1. My terraform files are
```hcl
resource "citrixadc_csvserver_cspolicy_binding" "cspolicy_binding" {
  for_each = { for citrixadc_csvserver_cspolicy_binding in var.citrixadc_csvserver_cspolicy_bindings :
    upper(citrixadc_csvserver_cspolicy_binding.name) => citrixadc_csvserver_cspolicy_binding
  }
  name            = each.value.name
  policyname      = citrixadc_cspolicy.cspolicy[upper(each.value.policyname)].policyname
  targetlbvserver = citrixadc_lbvserver.lbvserver[upper(each.value.targetlbvserver)].name
}
```
2. which terraform command I am getting the error
3. Terraform output logs
4. Error I am facing on the console
Error: [ERROR] nitro-go: Failed to update resource of type csvserver_cspolicy_binding,  err=failed: 599 Netscaler specific error ({ "errorcode": 695, "message": "Priority is mandatory for advanced expressions.", "severity": "ERROR" })

**Expected behaviour**
 cspolicy_bindings priority should auto increment the number by itself if not provided..

**Screenshots**

**Environment (please complete the following information):**
 - OS:Windows
- Terraform Version:1.3.6

**Comment by JonathanPSilva** [comment]
Same Issue using:

Terraform v1.7.5
+ provider registry.terraform.io/citrix/citrixadc v1.41.0
