### ISSUE TITLE
[FEATURE REQUEST] citrixadc_route - able to update or delete the default route

### ISSUE THREAD

**Issue by HS1542** [citrix/terraform-provider-citrixadc#1014]
# Case: We want to be able to change the gateway for the default route 0.0.0.0/0.0.0.0.
During provisioning of a VPX, you will at one time configure a NSIP and a default route.
Now, if you later on want to change the default route, after having added VLANs, SNIPS aso, 
you will have to add a second route for 0.0.0.0/0.0.0.0 and delete the original.

We cannot see any way of making the citrixadc_route resource either update or deleting an existing route?
So We kindly request a feature request to be to achieve changing the existing default route.
 
-BR

**Comment by rohit-myali** [comment]
Hi @HS1542 ,
We can manage/delete the default route by importing it to the Terraform using the `terraform import` command.

Demo video for the same can be found in the below link: https://citrix.sharefile.com/d-s4488373b583f42a8a988a4f30a27ff1e

**Comment by rohit-myali** [comment]
Hi @HS1542 , 
Were you able to refer to the video? I would like to hear updates from you to close this issue if everything is working fine!!

**Comment by HS1542** [comment]
@rohit-myali,
Yes, thank you. Leveraging terraform import first to get the state in solves this ticket.:)
