### ISSUE TITLE
[FEATURE REQUEST]  citrixadc_vpnvserver - ability to bind sslprofile?

### ISSUE THREAD

**Issue by HS1542** [citrix/terraform-provider-citrixadc#1016]
# Unable to select a sslprofile to use for vpn vserver?

I am not sure if this is a feature request or just a simple question? :)

Reading up the documentation for citrixadc_vpnvserver: https://registry.terraform.io/providers/citrix/citrixadc/latest/docs/resources/vpnvserver 
it seems like the attribute for selecting sslprofile is missing?
This is implemented for both citrixadc_lbvserver and citrixadc_csvserver, but not for citrixadc_vpnvserver?

Looking into the Citrix ADC Nitro API reference, I cannot see any reference to sslprofile for vpnvserver there either?
https://developer-docs.citrix.com/projects/citrix-adc-nitro-api-reference/en/latest/configuration/vpn/vpnvserver/

How are we ment to be able to select a ssl profile to be used by a VPN vserver?

We kindly request a way of binding a non-default ssl profile to a VPN vserver when "ssl parameter -defaultProfile ENABLED" is configured

**Comment by rohit-myali** [comment]
Hello @HS1542 
Can you please help me understand why you need this feature?

**Comment by HS1542** [comment]
I don't need this, but as I saw you had done an ehhancement for it for lbvserver and csvserver, I thought of keeping it open. Please close at your own will.

**Comment by rohit-myali** [comment]
Sure @HS1542 
As previously done in lbvserver and csvserver, we are not planning on combining binding with individual resources, as it creates complexity in implementing and debugging the resource..!!
