### ISSUE TITLE
[BUG] citrixadc_vpnvserver_appflowpolicy_binding - id should be based also upon bindpoint

### ISSUE THREAD

**Issue by HS1542** [citrix/terraform-provider-citrixadc#1017]
# citrixadc_vpnvserver_appflowpolicy_binding does not handle state correctly

I have one appflow policy, which I have bound to both REQUEST and ICA_REQUEST bindpoints.
Trying to rerun the terraform project, the provider will mix these two as the id is built up by vservername.policyname
Pretty much the same which happend here?:  https://github.com/citrix/terraform-provider-citrixadc/issues/963

```
-/+ resource "citrixadc_vpnvserver_appflowpolicy_binding" "appflow_pol_bind_1" {
      ~ bindpoint              = "REQUEST" -> "ICA_REQUEST" # forces replacement
      ~ groupextraction        = false -> (known after apply)
      ~ id                     = "<vserver.name>,<policy.name>" -> (known after apply)
        name                   = "<vserver.name>"
      ~ secondary              = false -> (known after apply)
        # (3 unchanged attributes hidden)
    }
```

I guess this could be the case for multiple policy types?
I kindly request that the ID is built by for instance <vserver.name>,<policy.name>,**<bind.point>**.

A workaround is to create different policies for each bindpoint with unique names.

**Comment by rohit-myali** [comment]
Hi @HS1542 
Thanks for the input. We will implement this soon and update you regarding this.

Thanks,
Rohit

**Comment by rohit-myali** [comment]
Hi @HS1542 
Thanks for your patience. I have worked on this resource and it is now available in the terraform registry. Please download the latest terraform-provider-citrixadc version v1.35.0.
Link to the [docs](https://registry.terraform.io/providers/citrix/citrixadc/latest/docs/resources/vpnvserver_appflowpolicy_binding)
