### ISSUE TITLE
Documentation issue for resource snmpcommunity

### ISSUE THREAD

**Issue by alpha69dk** [citrix/terraform-provider-citrixadc#1019]
In the documentation is stated "permissions" is an optional argument, but it is actually mandatory, since an error is thrown if missing.
Link = https://registry.terraform.io/providers/citrix/citrixadc/latest/docs/resources/snmpcommunity#permissions
Also - for reference it would be nice to have the possible values listed.

**Comment by rohit-myali** [comment]
Hello @alpha69dk 
Thanks for contacting us.

We have fixed this. Please refer to the documentation of [`citrixadc_snmpcommunity`](https://registry.terraform.io/providers/citrix/citrixadc/latest/docs/resources/snmpcommunity).

Please use our latest terraform provider [v1.36.0](https://registry.terraform.io/providers/citrix/citrixadc/latest/docs/resources/snmpcommunity)
