### ISSUE TITLE
[BUG] SNMPTrap in 1.33.0 not backwards compatible w/ previous versions

### ISSUE THREAD

**Issue by andrewhadam** [citrix/terraform-provider-citrixadc#1025]
# Contact us

> For any immediate issues or help , reach out to us at NetScaler-AutomationToolkit@cloud.com !

# Bug Report

**Describe the bug**
Because there is no logic for handling previous version's IDs, the snmp trap object when refreshing causing the provider to crash.

**To Reproduce**
Steps to reproduce the behaviour:
1. My terraform files are
Not config specific.  It's a provider version problem.

2. which terraform command I am getting the error
```
terraform plan/apply
```
3. Terraform output logs to the log file (./tf.log). Append `TF_LOG=TRACE NS_LOG=TRACE TF_LOG_PATH=./tf.log` to your terraform command
```bash
# terraform output logs.
```
4. Error I am facing on the console
```
Stack trace from the terraform-provider-citrixadc_v1.33.0 plugin:

panic: runtime error: index out of range [2] with length 2

goroutine 16 [running]:
github.com/citrix/terraform-provider-citrixadc/citrixadc.readSnmptrapFunc(0xc0007608c0, {0x2022e40?, 0xc000498780})
	github.com/citrix/terraform-provider-citrixadc/citrixadc/resource_citrixadc_snmptrap.go:115 +0x874
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000990820, 0xc000754870, {0x2022e40, 0xc000498780})
	github.com/hashicorp/terraform-plugin-sdk@v1.17.2/helper/schema/resource.go:470 +0x1aa
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadResource(0xc0004122c8, {0xc000b84240?, 0x11a2626?}, 0xc000b84240)
	github.com/hashicorp/terraform-plugin-sdk@v1.17.2/internal/helper/plugin/grpc_provider.go:535 +0x34b
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadResource_Handler({0x21f2b40?, 0xc0004122c8}, {0x26f6780, 0xc0007518f0}, 0xc0007603f0, 0x0)
	github.com/hashicorp/terraform-plugin-sdk@v1.17.2/internal/tfplugin5/tfplugin5.pb.go:3269 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00020c000, {0x26fa428, 0xc00043c9c0}, 0xc0006e5320, 0xc000a432c0, 0x2f8c5f0, 0x0)
	google.golang.org/grpc@v1.52.0/server.go:1336 +0xd13
google.golang.org/grpc.(*Server).handleStream(0xc00020c000, {0x26fa428, 0xc00043c9c0}, 0xc0006e5320, 0x0)
	google.golang.org/grpc@v1.52.0/server.go:1704 +0xa1b
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.52.0/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.52.0/server.go:963 +0x28a

Error: The terraform-provider-citrixadc_v1.33.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

```

**Expected behaviour**
This is similar to one of my previous tickets but if you're going to update the ID of a resource, there should be a way that it is backwards compatible because right now you have to manually nuke old resources to rebuild new ones to continue working.  This is not a good method of releasing new versions of resources.

**Environment (please fill the following information):**
Provider 1.33.0

**Comment by rohit-myali** [comment]
Hey @andrewhadam ,
Sorry for the inconvenience caused due to the change of id of the resource. We will try to handle these resource and update you soon on this resource. Thanks for raising this up.

Thanks,
Rohit

**Comment by rohit-myali** [comment]
Hi @andrewhadam, I have fixed the issue. I made the code backwards compatible. So, you can use the latest version of out Terraform Provider [v.134.0](https://registry.terraform.io/providers/citrix/citrixadc/latest/docs). And the state file will be updated without complaining. 
Thanks for contacting us.

Thanks
Rohit
