### ISSUE TITLE
[BUG] citrixadc_appfwprofile sqlinjectiononlycheckfieldswithsqlchars , stripcomments and xmlsqlinjectiononlycheckfieldswithsqlchars is set on every run

### ISSUE THREAD

**Issue by kaiAsmOne** [citrix/terraform-provider-citrixadc#1038]
# Contact us

> For any immediate issues or help , reach out to us at NetScaler-AutomationToolkit@cloud.com !

# Bug Report

Using resource "citrixadc_appfwprofile"
i set the following
      + sqlinjectiononlycheckfieldswithsqlchars    = "ON"
      + stripcomments                              = "OFF"
      + xmlsqlinjectiononlycheckfieldswithsqlchars = "ON"

Everytime i do a terraform apply it modifies all my AppFW Profiles as follows:  (Even though it is already set in the initial run)

   module.netscaler-adc-waf-app_company_com.citrixadc_appfwprofile.ns-app_waf will be updated in-place
  ~ resource "citrixadc_appfwprofile" "ns-app_waf" {
        id                                         = "app.companyname.com"
        name                                       = "app.companyname.com"
      + sqlinjectiononlycheckfieldswithsqlchars    = "ON"
      + stripcomments                              = "OFF"
      + xmlsqlinjectiononlycheckfieldswithsqlchars = "ON"

This does not break anything but my terraform apply spends quite alot of execution time on setting this for every run. 
(I have quite a lot of WAF profiles )

**To Reproduce**
Steps to reproduce the behaviour:
1. My terraform files are
```hcl
# my terraform script here
```
2. which terraform command I am getting the error
```bash
# terrafrom command
```
3. Terraform output logs to the log file (./tf.log). Append `TF_LOG=TRACE NS_LOG=TRACE TF_LOG_PATH=./tf.log` to your terraform command
```bash
# terraform output logs.
```
4. Error I am facing on the console
```bash
# console error
```

**Expected behaviour**

**Screenshots**

**Environment (please fill the following information):**
 - OS: Mac
 - `terraform version: Terraform v1.4.5
 - terraform-provider-citrixadc version: "1.34.0"

**Additional context**

**Comment by rohit-myali** [comment]
Hello @kaiAsmOne 
Thanks for contacting us. I have fixed this issue. I will update you soon once it is released to the terraform registry.

Thanks,
Rohit

**Comment by rohit-myali** [comment]
Hi @kaiAsmOne 
Thanks for reaching out to us.!!
I have updated the resource and it is now released to the terraform registry.
Please use the latest terraform-provider-Citrixadc version v.1.35.0.
link to the docs: https://registry.terraform.io/providers/citrix/citrixadc/latest/docs/resources/appfwprofile


Thanks
Rohit
