### ISSUE TITLE
[BUG] Changing cipheader on an already deployed servicegroup results in error

### ISSUE THREAD

**Issue by alpha69dk** [citrix/terraform-provider-citrixadc#1048]
# Bug Report

**Describe the bug**
When using citrixadc_servicegroup you can set cip and cipheader and succesfully deploy the servicegroup.
If you later want to change to another cipheader, then an error is shown during Apply = "Error: Error updating servicegroup"
If you manually delete the servicegroup, then it works (detecting the servicegroup is missing and needs to be created).

**To Reproduce**
Steps to reproduce the behaviour: (also see above description)

2. which terraform command I am getting the error
```bash
citrixadc_servicegroup
```
4. Error I am facing on the console
```bash
citrixadc_servicegroup.tf_servicegroup["dummysg"]: Modifying... [id=dummysg] 
│ Error: Error updating servicegroup dummysg 
│ with citrixadc_servicegroup.tf_servicegroup["dummysq"], 
│ on create_services.tf line 148, in resource "citrixadc_servicegroup" "tf_servicegroup": 
│ 148: resource "citrixadc_servicegroup" "tf_servicegroup" 
##[error]PowerShell exited with code '1'. 
```

**Expected behaviour**
Expected the cipheader value to be changed on the Service Group.

**Environment (please fill the following information):**
 - terraform-provider-citrixadc version = 1.35.0

**Comment by rohit-myali** [comment]
Hello @alpha69dk 
I have fixed this issue. We will release this into terraform registry in our next release. I will keep you Updated.

Thanks,
Rohit

**Comment by rohit-myali** [comment]
Hello @alpha69dk 
Thanks for contacting us.

We have fixed this issue. Please use our latest terraform provider [v1.36.0](https://registry.terraform.io/providers/citrix/citrixadc/latest/docs/resources/servicegroup)
