### ISSUE TITLE
[FEATURE REQUEST] Ensure all configuration changes are saved 

### ISSUE THREAD

**Issue by alpha69dk** [citrix/terraform-provider-citrixadc#1050]
# Feature Request

**Is your feature request related to a problem? Please describe.**
When configuration is changed using the NetScaler TF Provider then configuration is not necessarily saved.
This is true even if using nsconfig_save, as we cannot know when this is executed.
As a result, any changes done after nsconfig_save is not saved, and could be lost if NetScaler restarts.

**Describe the solution you'd like**
Ensure all configuration changes are saved (if using nsconfig_save)

**Describe alternatives you've considered**
Using dependencies and/or splitting into modules works, but creates unwanted complexity.

**Comment by rohit-myali** [comment]
Hello @alpha69dk 
Yes, you are correct that even if using `citrixadc_nsconfig_save`, we cannot know when this is executed.
I have researched on how to execute the resource block at the end, but I didn't find any inbuild functionalities given by Terraform.

So, It is also complex to create explicit dependency on `citrixadc_nsconfig_save` resources, as we may have many resources.

So, the workaround is to create a module of resources and create a dependency of that module inside the `citrixadc_nsconfig_save` resource.

**Example:**

```hcl

module "main-configs" {
  source = "../lbvserver"
}

resource "citrixadc_nsconfig_save" "save-config" {
  all        = true
  timestamp  = "2020-03-24T12:37:06Z"
  depends_on = [module.main-configs]
}

```

Please use the above workaround. Hope it helps you!!

**Comment by alpha69dk** [comment]
Thanks a lot for the suggestion. We already do a similar workaround but yours is simpler. I have suggested we use your workaround now :)
