### ISSUE TITLE
[BUG] import of user nsroot to the state.file results in 'username' being null

### ISSUE THREAD

**Issue by alpha69dk** [citrix/terraform-provider-citrixadc#1051]
# Bug Report

**Describe the bug**
During Terraform Import of user nsroot to the state.file the resulting 'username' is null.
This prevents further changes to the user (ie changing 'externalauth' or 'promptstring')

**Expected behaviour**
Username should be 'nsroot' - not null.

**Screenshots**
![image](https://github.com/citrix/terraform-provider-citrixadc/assets/80174994/0c4ab3a6-438e-4867-b5a1-03aec4953d1b)

**Comment by rohit-myali** [comment]
Hello @alpha69dk 
I have fixed this issue. We will release this into terraform registry in our next release. I will keep you Updated.

Thanks,
Rohit

**Comment by alpha69dk** [comment]
Thanks a lot @rohit-myali - much appreciated

**Comment by rohit-myali** [comment]
Hello @alpha69dk 
Thanks for contacting us.
I have fixed this issue. Please use our latest terraform provider [v1.36.0](https://registry.terraform.io/providers/citrix/citrixadc/latest/docs/resources/systemuser)

Thank You
Rohit
