### ISSUE TITLE
[FEATURE REQUEST] citrixadc_service - ability to bind sslprofile?

### ISSUE THREAD

**Issue by HS1542** [citrix/terraform-provider-citrixadc#1055]
Pretty much the same as for https://github.com/citrix/terraform-provider-citrixadc/issues/1016, but now in regards to service and sslprofile for backend.
You have to bind the sslprofile by using the citrixadc_sslservice, although the citrixadc_service supports creating service of type SSL.

**Comment by rohit-myali** [comment]
Hello @HS1542 
Can you please specify more on what you need exactly.

**Comment by HS1542** [comment]
This had me just confused that you could: 
create a service of type ssl using citrixadc_service, but not select a sslprofile on that resource
create a service of type ssl using citrixadc_sslservice, and there you can select a sslprofile
