### ISSUE TITLE
[FEATURE REQUEST] - Default Nonintrusive Profile Support on Bot Management Settings

### ISSUE THREAD

**Issue by adc-nerd** [citrix/terraform-provider-citrixadc#1056]
# Feature Request
"Bot Management Settings" includes a "Default Nonintrusive Profile" which is unknown in "citrixadc_botsettings".

**Describe the solution you'd like**
Would be great to set all "Bot Management Settings" with terraform (without an extra script).

**Additional context**
Documentation (https://registry.terraform.io/providers/citrix/citrixadc/latest/docs/resources/botsettings) is wrong.
Import is currently not supported by "citrixadc_botsettings". Looks like copy/paste from citrixadc_csaction.

**Comment by rohit-myali** [comment]
Hello @adc-nerd 
Thank you for contacting us.
We have added [`defaultnonintrusiveprofile`](https://registry.terraform.io/providers/citrix/citrixadc/latest/docs/resources/botsettings#defaultnonintrusiveprofile) attribute to the `citrixadc_botsettings` resource. Please use our latest terraform provider version [v1.36.0](https://registry.terraform.io/providers/citrix/citrixadc/latest/docs/resources/botsettings).

Thank you,
Rohit
