### ISSUE TITLE
Support for probeport and probeprotocol in lbvserver configuration

### ISSUE THREAD

**Issue by ranikaruna** [citrix/terraform-provider-citrixadc#1071]
On Netscaler for lbvserver configuration, we have two parameters - "probeport and probeprotocol", these parameters are used in UDP vserver configurations. Please find doc link for lb vserver as follows:
https://developer-docs.citrix.com/projects/netscaler-command-reference/en/latest/lb/lb-vserver/

CLI reference:
> add lb vserver v1  udp  -p
persistAVPno             persistenceType          **probePort**                probeSuccessResponseCode push                     pushMultiClients        
persistenceBackup        persistMask              **probeProtocol**            processLocal             pushLabel                pushVserver             

# Contact us

> For any immediate issues or help , reach out to us at NetScaler-AutomationToolkit@cloud.com !

# Feature Request

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by rohit-myali** [comment]
Hello @ranikaruna 
Thanks you for contacting us.
We have fixed this issue. Please use the latest terraform provider citrixadc v.1.36.0. 
Link to the documentation: https://registry.terraform.io/providers/citrix/citrixadc/latest/docs/resources/lbvserver#probeport

Thanks,
Rohit
