### ISSUE TITLE
Question about managing nsroot user

### ISSUE THREAD

**Issue by rhelfand** [citrix/terraform-provider-citrixadc#1075]
Hello,

Using: citrix/citrixadc version = "1.33.0"

I'm trying to understand how to manage the nsroot password in our environment.  We manage several Netscalers, and would like to pull the nsroot password from Vault and apply it using the citrixadc_systemuser resource.

However, attempting to do this I get an error that terraform wants to replace the resource, and an error stating that "The superuser cannot be removed."

```
Terraform will perform the following actions:

  # citrixadc_systemuser.make_nsroot_user must be replaced
-/+ resource "citrixadc_systemuser" "make_nsroot_user" {
      ~ externalauth   = "ENABLED" -> (known after apply)
      ~ hashedpassword = "*****" -> (known after apply)
      ~ id             = "nsroot" -> (known after apply)
      ~ logging        = "ENABLED" -> (known after apply)
      ~ maxsession     = 0 -> (known after apply)
      + password       = (sensitive value)
      + promptstring   = (known after apply)
      + username       = "nsroot" # forces replacement
        # (1 unchanged attribute hidden)
    }

Plan: 1 to add, 0 to change, 1 to destroy.
citrixadc_systemuser.make_nsroot_user: Destroying... [id=nsroot]
╷
│ Error: [INFO] delete failed: 599 Netscaler specific error ({ "errorcode": 359, "message": "The superuser cannot be removed", "severity": "ERROR" })
```

I believe that using "citrixadc_change_password" is possible, but this requires a "current password" and "new password," and current password would be a different value for a new deployment versus a password reset, which seems confusing.  Any help would be appreciated.

**Comment by rhelfand** [comment]
I think this can probably be closed.  I just found the "password_resetter" resource!

https://registry.terraform.io/providers/citrix/citrixadc/latest/docs/resources/password_resetter

**Comment by rohit-myali** [comment]
Hey @rhelfand 
Thanks for updating us.!!!
