### ISSUE TITLE
[BUG] - Error updating snmpalarm

### ISSUE THREAD

**Issue by adc-nerd** [citrix/terraform-provider-citrixadc#1077]
# Bug Report

**Describe the bug**
snmpalarm settings of AVERAGE-CPU and PORT-ALLOC-EXCEED are not correctly read.

**To Reproduce**
Steps to reproduce the behaviour:
1. My terraform files are
```hcl
resource "citrixadc_snmpalarm" "snmpalarm_avg_cpu_usage" {
  trapname 	 = "AVERAGE-CPU"
  thresholdvalue = 80
  normalvalue    = 80
  state          = "ENABLED"
  severity       = "Warning"
  logging	 = "ENABLED"
}
resource "citrixadc_snmpalarm" "snmpalarm_port_alloc_exceed" {
  trapname 	 = "PORT-ALLOC-EXCEED"
  thresholdvalue = 80
  normalvalue    = 80
  state          = "ENABLED"
  severity       = "Warning"
  logging	 = "ENABLED"
  time		 = 1800
}
```
2. which terraform command I am getting the error
```cmd
terrafrom plan/apply
```
3. Terraform output
Initial plan/apply works fine. Second plan/apply without any changes to the ressource files indicates that the normal values are 0, which is not the case. 

**Expected behaviour**
Successful configuration of all SNMP Alarms.

 - OS: Windows
- Terraform: v1.5.5
- citrixadc: v1.36.0

**Comment by rohit-myali** [comment]
Hey @adc-nerd 
Thanks for raising this issue.  We have addressed this issue and is released to the terraform registry.
Please use the latest terraform provider [v1.37.0](https://registry.terraform.io/providers/citrix/citrixadc/latest/docs).
