### ISSUE TITLE
[General Guidance]  - nsrpcnode secure "on" or "yes"

### ISSUE THREAD

**Issue by adc-nerd** [citrix/terraform-provider-citrixadc#1080]
**Question/Description**
Which values are correct for "secure" on "nsrpcnode"?
[Argument Reference](https://registry.terraform.io/providers/citrix/citrixadc/latest/docs/resources/nsrpcnode#argument-reference) states "YES|NO" - provided example uses "ON".
Tried with "YES" which seems to be fine but on second run terraform indicates to change "ON" to "YES". 

**To Reproduce**
Steps to reproduce the behaviour:
1. My terraform files are
```hcl
resource "citrixadc_nsrpcnode" "netscaler2on1" {
  ...
  secure    = "YES"
  ...
}
```
2. which terraform command I am getting the error
```cmd
terraform plan
terraform apply
```

**Environment:**
OS: Windows
Terraform: v1.5.5
citrixadc: v1.36.0

**Comment by rohit-myali** [comment]
Hey @adc-nerd 
Thanks for raising this issue.
We have updated the documentation for `citrixadc_nsrpcnode`. Please find the link to the docs [HERE](https://registry.terraform.io/providers/citrix/citrixadc/latest/docs/resources/nsrpcnode#secure)
