### ISSUE TITLE
[BUG] changing sslprofiletype in citrixadc/sslprofile-resource

### ISSUE THREAD

**Issue by StizLor** [citrix/terraform-provider-citrixadc#1081]
# Bug Report

**Describe the bug**
Changing the "sslprofiletype" of a "citrixadc/sslprofile"-resource will be be recognized by terraform as a change of the resource instead of a replacement. 

**To Reproduce**

1. create a minimalistic sslprofile-resource
```
resource "citrixadc_sslprofile" "test_sslprofile" {
  name  = "test_sslprofile"
  sslprofiletype = "FrontEnd"
}
```
2. create resource
`terraform apply -auto-approve`

3. change sslprofiletype in resource
```
resource "citrixadc_sslprofile" "test_sslprofile" {
  name  = "test_sslprofile"
  sslprofiletype = "BackEnd"
}
```
4. apply new resource config
`terraform apply`
before accepting change terraform shows changes 
![Screenshot from 2023-08-24 07-14-01](https://github.com/citrix/terraform-provider-citrixadc/assets/80175994/fc493fc0-1677-43fb-9146-e678da5957fd)

5. when changes are accepted an error is shown
![Screenshot from 2023-08-24 07-15-30](https://github.com/citrix/terraform-provider-citrixadc/assets/80175994/fb2c8a91-c683-43f3-b1c9-9e966eb60d24)

**Expected behaviour**

Changing the "sslprofiletype" within an "citrixadc_sslprofile"-resource should lead to a replacement (destroy current and create anew) of the resource.

Workaround:
Run terraform apply with explicit replacement:
`terraform apply -replace="citrixadc_sslprofile.test_sslprofile"`

**Environment (please fill the following information):**
 - OS: Linux (Debian GNU/Linux 11 (bullseye) [11.7])
 - Terraform version:  v1.5.4 (on linux_amd64)
 - Provider: registry.terraform.io/citrix/citrixadc v1.36.0

**Comment by ravager-dk** [comment]
Suggestion would be to add ForceNew to true in the schema for sslprofiletype argument. I can create a PR for this later.

**Comment by rohit-myali** [comment]
Hey @ravager-dk thanks for the PR for this.
Hello @StizLor, this issue is being handeled now. Please use the latest terraform-provider-citrixadc [v1.37.0](https://registry.terraform.io/providers/citrix/citrixadc/latest/docs).
Link to the documentation: [`citrixadc_sslprofile`](https://registry.terraform.io/providers/citrix/citrixadc/latest/docs/resources/sslprofile)

Thanks
Rohit
