### ISSUE TITLE
[FEATURE REQUEST] add servemode argument to citrixadc_analyticsprofile

### ISSUE THREAD

**Issue by ravager-dk** [citrix/terraform-provider-citrixadc#1086]
# Contact us

> For any immediate issues or help , reach out to us at NetScaler-AutomationToolkit@cloud.com !

# Feature Request

**Is your feature request related to a problem? Please describe.**
Servemode argument is missing from the analyticsprofile ressource

**Describe the solution you'd like**
Add optional "servemode" argument with "pull,push" as options (push is default).

**Describe alternatives you've considered**
Requires manuel generic rest call to reconfigure an analytics profile to pull, which is not ideal.

**Additional context**
The feature is required for setting up a pull prometheus profile

**Comment by rohit-myali** [comment]
Hey @ravager-dk 
Thanks for raising this request. We have worked on this feature request. Please use the latest terraform-provider-citrixadc [v1.37.0](https://registry.terraform.io/providers/citrix/citrixadc/latest/docs). 
Link to the documentation: [`citrixadc_analyticsprofile`](https://registry.terraform.io/providers/citrix/citrixadc/latest/docs/resources/analyticsprofile#servemode)

Thanks
Rohit
