### ISSUE TITLE
[BUG] resource "citrixadc_lbvserver_responderpolicy_binding" "tf_responder_policy_bind" Root resource was present, but now absent

### ISSUE THREAD

**Issue by Toasty-Roach** [citrix/terraform-provider-citrixadc#1088]
# Contact us

> For any immediate issues or help , reach out to us at NetScaler-AutomationToolkit@cloud.com !

# Bug Report

When binding a responder policy to a LBVserver the following error occurs. The policy gets bound but terarform produces an error.

**To Reproduce**
Steps to reproduce the behaviour:
1. My terraform files are
```hcl
resource "citrixadc_lbvserver_responderpolicy_binding" "tf_responder_policy_bind" {
  name = citrixadc_lbvserver.tf_lbvserver.name
  policyname = "Enforce_HSTS"
  priority = 100
  gotopriorityexpression = "END"
  bindpoint = "RESPONSE"
}
```
2. which terraform command I am getting the error
```bash
terraform apply
```

4. Error I am facing on the console
```bash
│ Error: Provider produced inconsistent result after apply
│
│ When applying changes to module.Webvip.citrixadc_lbvserver_responderpolicy_binding.tf_responder_policy_bind, provider "module.Webvip.provider[\"registry.terraform.io/citrix/citrixadc\"]" produced an unexpected new value: Root resource was present, but now absent.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

**Expected behaviour**
A Rewrite policy to the RESPONSE applied to the LBVserver and no Terraform errors

**Environment (please fill the following information):**
 - OS: Windows
Terraform v1.2.3
on windows_amd64
+ provider registry.terraform.io/citrix/citrixadc v1.36.0

**Comment by rohit-myali** [comment]
Hello @Toasty-Roach 
Thanks for reaching us.

Is `Enforce_HSTS` a `responderpolicy` or `rewritepolicy`. If it is a `rewritepolicy` then use `citrixadc_lbvserver_rewritepolicy_binding` resource for binding it to lbverver.

**Comment by Toasty-Roach** [comment]
Thanks Rohit-Myali it appears you are correct, I had the wrong resource policy binding. Changing things and it corrected it.
