### ISSUE TITLE
[BUG] citrixadc_nspbr attribute srcip is declared as bool

### ISSUE THREAD

**Issue by kaiAsmOne** [citrix/terraform-provider-citrixadc#1090]
# Contact us

> For any immediate issues or help , reach out to us at NetScaler-AutomationToolkit@cloud.com !

# Bug Report

When adding a Policy Based Route using citrixadc_nspbr
The attribute is in the terraform provider code declared as a boolean
Hence it is not possible to set value according to documentation

i.e srcip = "192.168.17.1-192.168.17.62"

**To Reproduce**
Steps to reproduce the behaviour:

resource "citrixadc_nspbr" "systemNetworkConfig_PBR_VLAN3" {
  name       = "VLAN_3"
  action     = "ALLOW"
  nexthop    = "true"
  srcip = "192.168.17.1-192.168.17.62"
  destipop = "NEQ"
  destip = "192.168.17.1-192.168.17.62"
  nexthopval = "192.168.17.62"
  vlan = "3"
}

# my terraform script here
```
2. which terraform command I am getting the error

│ Error: Incorrect attribute value type
│ 
│   on main.tf line 196, in resource "citrixadc_nspbr" "systemNetworkConfig_PBR_VLAN3":
│  196:   srcip = "192.168.17.1-192.168.17.62"
│ 
│ Inappropriate value for attribute "srcip": a bool is required.



# terrafrom command
```
3. Terraform output logs to the log file (./tf.log). Append `TF_LOG=TRACE NS_LOG=TRACE TF_LOG_PATH=./tf.log` to your terraform command
```bash
# terraform output logs.
```
4. Error I am facing on the console
```bash
# console error
```

**Expected behaviour**

**Screenshots**

**Environment (please fill the following information):**
 - OS: Mac
 - `terraform version`:  v1.4.5
 - terraform-provider-citrixadc version "1.35.0"
 - `go version` output

**Additional context**

**Comment by rohit-myali** [comment]
Hello @kaiAsmOne 
Thanks for raising this issue.

Yes `srcip` is bool, it should be `true` if you want to provide srcip and you need to provider srcip in the attribute named `srcipval`
Try to assign `true` to `srcip` and srcips in `srcipval`. And run the scripts.
Update me here after you try it.

Thanks,
Rohit

**Comment by kaiAsmOne** [comment]
Thank you sir !!

The documentation on srcip is abit confusing on 

https://registry.terraform.io/providers/citrix/citrixadc/latest/docs/resources/nspbr

Documentation on srcip attribute is as follows:

[srcip](https://registry.terraform.io/providers/citrix/citrixadc/latest/docs/resources/nspbr#srcip) - (Optional) IP address or range of IP addresses to match against the source IP address of an outgoing IPv4 packet. In the command line interface, separate the range with a hyphen. For example: 10.102.29.30-10.102.29.189.

**Comment by rohit-myali** [comment]
Thanks @kaiAsmOne ,
We will update the docs!!!
