### ISSUE TITLE
[FEATURE REQUEST] LB Service binding order option

### ISSUE THREAD

**Issue by jeffriechers** [citrix/terraform-provider-citrixadc#1094]
GSLB services now support Order binding for services to replace Backup Virtual Server options for Active:Passive.

Can this feature get added to the terraform code.

**Comment by rohit-myali** [comment]
Hey @jeffriechers 
Can you specify which services binding are you referring to? 
Please provide the equivalent CLI command or API reference for the same.

**Comment by jeffriechers** [comment]
Sorry, should have provided that info.  Living in Nyquil land the last few days.

Here is the GUI and CLI
https://docs.netscaler.com/en-us/citrix-adc/current-release/load-balancing/load-balancing-priority-order-services.html

And here is the API reference
https://developer-docs.netscaler.com/en-us/adc-nitro-api/current-release/configuration/lb/lbvserver_service_binding.html

Let me know if you need any more info.

**Comment by rohit-myali** [comment]
Thanks @jeffriechers 
This is enough for us to implement it. I will update you soon on this!!

**Comment by rohit-myali** [comment]
Hey @jeffriechers 
Thanks for raising this request. We have worked on this feature request. Please use the latest terraform-provider-citrixadc [v1.37.0](https://registry.terraform.io/providers/citrix/citrixadc/latest/docs). Link to the documentation: [`lbvserver_service_binding`](https://registry.terraform.io/providers/citrix/citrixadc/latest/docs/resources/lbvserver_service_binding#order)

Thanks
Rohit

**Comment by jeffriechers** [comment]
I do see that on the lbvserver, thank you.

Can we get it added to the *gslbvserver_gslbservice_binding *as well?

**Comment by rohit-myali** [comment]
Sure @jeffriechers 
We will consider it in our next releases!!
Thanks
