### ISSUE TITLE
Missing comma separated value

### ISSUE THREAD

**Issue by rafaelpirolla** [citrix/terraform-provider-citrixadc#1096]
https://github.com/citrix/terraform-provider-citrixadc/blob/2edd6f1979b27b9f4cbd1943be3f8f57e807e017/citrixadc/resource_citrixadc_dnsaddrec.go#L91C3-L91C3

Hi, I've noticed that in past versions you didn't store the ID with a comma separated value of hostname,ip.
If I've applied in a past version how should I upgrade the provider? Currently I need to manually download, edit and upload the terraform state file to S3 bucket...

Can't you get the hostname and ip form the fields instead of the id?

Thanks,
Rafael

**Comment by rohit-myali** [comment]
Hello @rafaelpirolla 
Thanks for raising this issue. We have addressed it in the provider release [v1.37.0](https://registry.terraform.io/providers/citrix/citrixadc/latest/docs). Please use the lastest terraform provider citrixadc v1.37.0. It would solve your issue.
