### ISSUE TITLE
[FEATURE REQUEST] citrixadc_sslcrl

### ISSUE THREAD

**Issue by HS1542** [citrix/terraform-provider-citrixadc#1109]
The function to create resources of type sslcrl seems missing from the provider?

sslcrl is required to be able to enforce CRL checks on mTLS connections.

ref: https://developer-docs.netscaler.com/en-us/adc-nitro-api/current-release/configuration/ssl/sslcrl

**Comment by rohit-myali** [comment]
Hello @HS1542 
Can you provide us equivalent NScli command? So, that it will be easy for our testing

Thanks
Rohit

**Comment by HS1542** [comment]
Hello,

There are some prerequisites to add a sslcrl.
1: You will have to upload and add a certificate to the configuration before
2: You have to have uploaded a base CRL before adding the sslcrl to the  configuration with refresh enabled (it has to read the CRLDPs I assume)

add ssl crl crl_file /var/netscaler/ssl/crl.pem -cacert CAcert -refresh ENABLE -time 01:00

ref:
https://developer-docs.netscaler.com/en-us/adc-command-reference-int/current-release/ssl/ssl-crl.html

**Comment by rohit-myali** [comment]
Hello @HS1542 
Thanks for raising this feature request.
We have worked on this and and it is now available in the terraform registry. Please download the latest terraform-provider-citrixadc version v1.38.0.

Link to documentation [HERE](https://registry.terraform.io/providers/citrix/citrixadc/latest/docs/resources/sslcrl)

**Comment by HS1542** [comment]
Great, thank you!
