### ISSUE TITLE
[BUG] citrixadc_vpnsessionaction - does not fetch correct state

### ISSUE THREAD

**Issue by HS1542** [citrix/terraform-provider-citrixadc#1110]
When subsequently running the project, the vpnsessionaction resource will reapply some parameters on every run (not changing as it does not know the value).
It seems that it does not fetch the correct state after having set the values or during planning
I have yet only discovered it for clientdebug, clientoptions, epaclienttype and windowsclienttype:

```
# citrixadc_vpnsessionaction.vpn_sess_act_gw will be updated in-place
  ~ resource "citrixadc_vpnsessionaction" "vpn_sess_act_gw" {
      + clientdebug                = "OFF"
      + clientoptions              = "all"
      + epaclienttype              = "AGENT"
        id                         = "vpn_sess_act-gw"
        name                       = "vpn_sess_act-gw"
      + windowsclienttype          = "AGENT"
        # (23 unchanged attributes hidden)
    }
```

**Comment by rohit-myali** [comment]
Hello @HS1542 
Thanks for raising the issue.
Can you please paste your terraform configuration, We will try to reproduce this and update you on this!

Thankss

**Comment by HS1542** [comment]
I do not longer have access to the code repository, but If I recall correctly it was reproducable by just creating a vpnsessionaction resource and specifying the a value for clientdebug, clientoptions, epaclienttype and windowsclienttype.
Running the project would set the values correctly, but the state would not fetch the correct values, so at every rerun, the values would be set anew, hence the + sign


resource "citrixadc_vpnsessionaction" "tf_sessionaction" {
    clientdebug                = "OFF"
    clientoptions              = "all"
    epaclienttype              = "AGENT"
    windowsclienttype          = "AGENT"
    name                       = "newsession"
    sesstimeout                = "10"
    defaultauthorizationaction = "ALLOW"
    transparentinterception    = "ON"
    clientidletimeout          = "10"
    sso                        = "ON"
    icaproxy                   = "ON"
    wihome                     = "https://citrix.lab.com"
    clientlessvpnmode          = "DISABLED"
}

**Comment by rohit-myali** [comment]
Hello @HS1542 
We have worked on this bug and it is now available in the terraform registry. Please download the latest terraform-provider-citrixadc version v1.38.0.

Thank You

**Comment by HS1542** [comment]
Great, thank you!
