### ISSUE TITLE
[FEATURE REQUEST] citrixadc_appfwsignatures : AutoEnable New Signatures missing

### ISSUE THREAD

**Issue by kaiAsmOne** [citrix/terraform-provider-citrixadc#1112]
# Contact us

> For any immediate issues or help , reach out to us at NetScaler-AutomationToolkit@cloud.com !

# Feature Request

The citrixadc_appfwsignatures does not have an argument / attribute
to "Auto Enable new Signatutes" 

(related to a deployment with auto upgrade signatures is enabled, all new downloaded signatures will stay in enabled="off" mode)

**Comment by kaiAsmOne** [comment]
The API appfwsignatures covers this with the autoenablenewsignatures argument / attribute

https://developer-docs.netscaler.com/en-us/adc-nitro-api/13-1/configuration/appfw/appfwsignatures

**Comment by rohit-myali** [comment]
Hello @kaiAsmOne 
Thanks for your patience.
We have worked on this enhancement and it is now available in the terraform registry. Please download the latest terraform-provider-citrixadc version v1.38.0.

Link to docs [HERE](https://registry.terraform.io/providers/citrix/citrixadc/latest/docs/resources/appfwsignatures#autoenablenewsignatures)
