### ISSUE TITLE
[FEATURE REQUEST] AppFW Signatures: Not possible to enable / disable a Signature using terraform

### ISSUE THREAD

**Issue by kaiAsmOne** [citrix/terraform-provider-citrixadc#1113]
# Contact us

> For any immediate issues or help , reach out to us at NetScaler-AutomationToolkit@cloud.com !

# Feature Request

When a Netscaler is fully deployed and configured using terraform there is no way to modify the WAF Signature File for a given web application.
 
I need to be able to change the xml file with the signatures.

I need to be able to have a terraform resource where i can specify the signature name (name of signature in gui) , the SignatureRule id 

And allow me to  specify the rule id actions Enabled / Block / Log / Stats / Remove / xout options for a specific rule id.

**Comment by kaiAsmOne** [comment]
After doing some nstrace it would be enough for me to have the functions / attributes of the appfwsignatures  API implemented . (ruleid , category , enabled, action)

https://developer-docs.netscaler.com/en-us/adc-nitro-api/13-1/configuration/appfw/appfwsignatures

**Comment by rohit-myali** [comment]
Hello @kaiAsmOne 
Thanks for raising this feature request.
We have released this and it is now available in the terraform registry. Please download the latest terraform-provider-citrixadc version v1.38.0.

Link to documentation [HERE](https://registry.terraform.io/providers/citrix/citrixadc/latest/docs/resources/appfwsignatures#ruleid)

**Comment by kaiAsmOne** [comment]
@rohit-myali : I have tried upgrading to 1.39.0 provider but for every terraform apply the provider now wants to replace the signatures on each run.. The provider seems to belive it is changed on each run as follows

# module.netscaler-adc-waf-fqdn_company_no.citrixadc_appfwsignatures.app_waf must be replaced
-/+ resource "citrixadc_appfwsignatures" "app_waf" {
      + action                  = (known after apply) # forces replacement
      + autoenablenewsignatures = (known after apply)
      + category                = (known after apply)
      + enabled                 = (known after apply)
      ~ id                      = "waf_sig_fqdn.company.no" -> (known after apply)
      + mergedefault            = (known after apply)
        name                    = "waf_sig_fqdn.company.no"
      + ruleid                  = (known after apply) # forces replacement
      + sha1                    = (known after apply)
      + vendortype              = (known after apply)
      + xslt                    = (known after apply)
        # (5 unchanged attributes hidden)
    }
