### ISSUE TITLE
[FEATURE REQUEST] citrixadc_analyticsprofile global binding

### ISSUE THREAD

**Issue by arne-marien** [citrix/terraform-provider-citrixadc#1117]
# Feature Request
Currently, the Terraform provider does not support binding Analytics Profiles globally. There are already resources to bind the profile to various VServers. However, a resource for the global bind is also required.

**Describe the solution you'd like**
```
bind analytics global ns_analytics_test_profile
```

**Describe alternatives you've considered**
Bind via Nitro API in Null Resource as a workaround.

**Additional context**
-

**Comment by arne-marien** [comment]
*Bump up*. Do you had time to review this?

**Comment by rohit-myali** [comment]
Hey @arne-marien 
Thanks for contacting us.
We will be looking into this soon and will be included in our next releases.

I will update you on this.


Thanks!!

**Comment by rohit-myali** [comment]
Hello @arne-marien 
Thanks for raising this request.
We have worked on this and and it is now available in the terraform registry. Please download the latest terraform-provider-citrixadc version v1.38.0.

Link to documentation [HERE](https://registry.terraform.io/providers/citrix/citrixadc/latest/docs/resources/analyticsglobal_analyticsprofile_binding)
