### ISSUE TITLE
[BUG] deviation parameter on lbmonitor causes an error

### ISSUE THREAD

**Issue by gusmb** [citrix/terraform-provider-citrixadc#1123]
# Contact us

> For any immediate issues or help , reach out to us at NetScaler-AutomationToolkit@cloud.com !

# Bug Report

Given the following configuration example for lbmonitor:

![image](https://github.com/citrix/terraform-provider-citrixadc/assets/44675960/d36b6593-dc77-474f-b458-43e854ebaa30)

Terraform validate and plan work correctly, but when I try to apply I get the error:

![image](https://github.com/citrix/terraform-provider-citrixadc/assets/44675960/1262e769-ed97-4502-835d-07c308771b1d)
 
The error suggests that units argument is a pre-req of deviation, but units is not a valid argument according to the docs: https://registry.terraform.io/providers/citrix/citrixadc/latest/docs/resources/lbmonitor
Instead, I provided units1, units2, units3 and units4.

**To Reproduce**
Steps to reproduce the behaviour:
1. My terraform files are (See above)

2. which terraform command I am getting the error
```bash
# terrafrom apply
```
3. Terraform output logs to the log file (./tf.log). Append `TF_LOG=TRACE NS_LOG=TRACE TF_LOG_PATH=./tf.log` to your terraform command (See above)

4. Error I am facing on the console (See above)

**Expected behaviour**
I would expect the resource to be properly applied as the units1 parameter is specified as an argument dependency of "deviation"

**Screenshots**
See above

**Environment (please fill the following information):**
 - OS: Linux
 - terraform-provider-citrixadc v1.37.0
 - `go version` 1.21.3

**Comment by sumanth-lingappa** [comment]
@rohit-myali,
Looks similar to https://github.com/netscaler/ansible-collection-netscaleradc/pull/333/files
Please check.

**Comment by gusmb** [comment]
Ok so what I've noticed by running a few terraform tests is that the issue seems to be only when deviation = 0.  In that case, it might be that terraform omits this as it has the default value and then complains about a missing value? When I configure deviation set to any other value, Terraform works as expected (I have also tried with values > 60)

**Comment by rohit-myali** [comment]
Hello @gusmb 
Thanks for raising the issue.
I will work on this and update you as soon as we release it to terraform registry.

**Comment by rohit-myali** [comment]
Hey @gusmb 
We have released this and it is now available in the terraform registry. Please download the latest terraform-provider-citrixadc version v1.38.0.
