### ISSUE TITLE
[BUG] Terraform reports failed to updated lb_algorithm on lbvserver but it is correctly updated on the device

### ISSUE THREAD

**Issue by gusmb** [citrix/terraform-provider-citrixadc#1124]
# Contact us

> For any immediate issues or help , reach out to us at NetScaler-AutomationToolkit@cloud.com !

# Bug Report

Given the following example:

```
resource "citrixadc_lbvserver" "sample-app-slb-80" {
  ipv46      = "10.0.1.1"
  port      = 80
  state      = "ENABLED"
  lbmethod      = "LEASTCONNECTION"
  servicetype      = "TCP"
  timeout      = 2
  clttimeout      = 300
  name      = "V_SAMPLE_APP_80"
  persistencetype      = "SOURCEIP"
}
```

When I try to update `LEASTCONNECTION` to `ROUNROBIN`, the terraform plan command shows the right output, but this happens when I do the apply:

```
 # citrixadc_lbvserver.neo-app1-slb-80 will be updated in-place
  ~ resource "citrixadc_lbvserver" "sample-app1-slb-80" {
        id                                 = "V_SAMPLE_APP_80"
      ~ lbmethod                           = "LEASTCONNECTION" -> "ROUNDROBIN"
        name                               = "V_SAMPLE_APP_80"
        # (56 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

citrixadc_lbvserver.sample-app-slb-80: Modifying... [id=V_SAMPLE_APP_80]
╷
│ Error: [ERROR] netscaler-provider: Error updating lbvserver V_SAMPLE_APP_80
│
│   with citrixadc_lbvserver.sample-app-slb-80,
│   on terraform_main.tf line 32, in resource "citrixadc_lbvserver" "sample-app-slb-80":
│   32: resource "citrixadc_lbvserver" "sample-app-slb-80" {
```
The error message just sais `Error: [ERROR] netscaler-provider: Error updating lbvserver V_SAMPLE_APP_80`. However, when I login to the device and check the config, the change has been applied, and the TF state has been updated accordingly, so a subsequent terraform plan does not report changes.

This looks like a bug on the terraform module side.

**To Reproduce**
Steps to reproduce the behaviour:

See above

**Expected behaviour**
Expect to successfully push the changes as reported by the terraform plan. Given that the config is actually applied correctly, the error message is puzzling.

**Screenshots**

**Environment (please fill the following information):**
 - OS: Linux
 - `terraform version`  v1.5.7
 - terraform-provider-citrixadc version 1.37.0
 - `go version` output 1.21.3

**Additional context**

**Comment by rohit-myali** [comment]
Hello @gusmb ,
You mentioned "When I try to update `LEASTCONNECTION` to `ROUNROBIN`"

I see that, you have mentioned `ROUNROBIN` but it should be `ROUNDROBIN`, Can you please check your configuration and update me here?

**Comment by gusmb** [comment]
> Hello @gusmb , You mentioned "When I try to update `LEASTCONNECTION` to `ROUNROBIN`"
> 
> I see that, you have mentioned `ROUNROBIN` but it should be `ROUNDROBIN`, Can you please check your configuration and update me here?

This is just a typo when I wrote the issue. The configuration I used was correct

**Comment by rohit-myali** [comment]
Can you run the same terraform configuration with the logging, 
`NS_LOG=TRACE TF_LOG=TRACE TF_LOG_PATH=./tf.log terraform apply`, this will create log file `tf.log`, can you please paste the error present in the logfile?

**Comment by gusmb** [comment]
These are the relevant lines:

``` 
0 [DEBUG] provider.terraform-provider-citrixadc_v1.37.0:   resourceJSON=

2024-04-03T17:07:26.114-0400 [DEBUG] provider.terraform-provider-citrixadc_v1.37.0:   | {"lbvserver":{"lbmethod":"ROUNDROBIN","name":"V_SAMPLE_APP_80","timeout":0}}


2024-04-03T17:07:26.331-0400 [DEBUG] provider.terraform-provider-citrixadc_v1.37.0: 2024-04-03T17:07:26.331-0400 [INFO]  service/netscaler_resource.go:101: nitro-go: error = : body="{ "errorcode": 2136, "message": "Timeout value out of range; enter a value between 2 minutes and 1440 minutes", "severity": "ERROR" }"


2024-04-03T17:07:26.337-0400 [ERROR] vertex "citrixadc_lbvserver.sample-app-slb-80" error: [ERROR] netscaler-provider: Error updating lbvserver V_SAMPLE_APP_80
```

It seems like the update payload includes a `timeout=0` value as well, even though it doesn't show in the TF plan, since the only thing I did is change `LEASTCONNECTION` to `ROUNDROBIN`. Seems like it didn't like the timeout value, and also explains why the LB algorithm is correctly apply regardless of the error

**Comment by rohit-myali** [comment]
Hi @gusmb 
What terraform citrixadc provider version are you using?
If you are using the older version can you upgrade it to out latest version?
https://registry.terraform.io/providers/citrix/citrixadc/latest/docs

**Comment by gusmb** [comment]
It is the latest I believe, 1.37

**Comment by rohit-myali** [comment]
We have Updated out resource, `lbvserver for the attribute `timeout` to omit the 0 value!! It is updated in our most recent  release.

**Comment by gusmb** [comment]
Hi @rohit-myali , I seem to be on the right version:

```
terraform {
  backend "http" {}
  required_providers {
    citrixadc = {
      source  = "citrix/citrixadc"
      version = "~> 1.37.0"
    }
  }
}
```

```
✗ terraform version
Terraform v1.7.5
on linux_amd64
+ provider [registry.terraform.io/citrix/citrixadc](http://registry.terraform.io/citrix/citrixadc) v1.37.0
```

But I am getting the issue on this version

**Comment by rohit-myali** [comment]
Hey @gusmb 
Thanks for your time. We have update the provider code. This will be included as part of our next terraform release. I will update you on this!!

Thanks

**Comment by rohit-myali** [comment]
Hello @gusmb 
We have worked on this resource and it is now available in the terraform registry. Please download the latest terraform-provider-citrixadc version v1.38.0. 

Link to docs: https://registry.terraform.io/providers/citrix/citrixadc/latest/docs

**Comment by rohit-myali** [comment]
Hello @gusmb 
We have worked on this resource and it is now available in the terraform registry. 
Please download the latest terraform-provider-citrixadc version v1.38.0.
