### ISSUE TITLE
[FEATURE REQUEST]  Add attribute support to gslbservicegroup resource

### ISSUE THREAD

**Issue by gusmb** [citrix/terraform-provider-citrixadc#1127]
# Contact us

> For any immediate issues or help , reach out to us at NetScaler-AutomationToolkit@cloud.com !

# Feature Request

I want to configure gslbservicegroup (https://registry.terraform.io/providers/citrix/citrixadc/latest/docs/resources/gslbservicegroup) in a similar way as servicegroup for SLB, managing the bindings implicitly and not explicitly by defining them separately. The following requirements need to be met:

- gslbservicegroup can be bound to multiple members
- gslbservicegroup can be bound to a gslbvserver
- gslbservicegroup can be bound to multiple monitors

**Describe the solution you'd like**
Would like to be able to define the gslbservicegroup with all implicit bindings, like this:

```
resource "citrixadc_gslbservicegroup" "tf_gslbservicegroup" {
  servicegroupname = "test_gslbvservicegroup"
  servicetype      = "HTTP"
  cip              = "DISABLED"
  sitename         = citrixadc_gslbsite.site_local.sitename
  gslbservicegroupmembers = ["172.20.0.9:80:10", "172.20.0.10:80:10", "172.20.0.11:8080:20"]
  gslbvservers = [ citrixadc_lbvserver.tf_lbvserver1.name, citrixadc_lbvserver.tf_lbvserver2.name ]
  lbmonitorbinding = [
    {
      monitor_name = "mymonitor"
      monstate = "ENABLED"
      weight = 1
    }
  ]
}
```

Since servicegroup member can be in this case server or SLB vips, the setting might need to be flexible to specify server by name or just VIP address (IP based binding)

**Describe alternatives you've considered**
Doing explicit bindings using separate resource objects. I would like to avoid this if possible

**Additional context**

**Comment by gusmb** [comment]
Also, there is even no explicit way to bind gslbservicegroup with members at this point

**Comment by rohit-myali** [comment]
Hey @gusmb 

we are not planning on combining binding with individual resources, as it creates complexity in implementing and debugging the resource.

So, I have implemented new resource to bind `gslbservicegroup` to gslbservicegroupmembers`, which will be released today to the terraform registry. I will update you post release.

Thanks
