### ISSUE TITLE
[BUG] citrixadc_servicegroup - netprofile cannot be removed from configuration

### ISSUE THREAD

**Issue by alexander-wetzling** [citrix/terraform-provider-citrixadc#1128]
Bug Report
I set a netprofile via citrixadc_servicegroup resource and it was added successfully.
If I now remove the netprofile completely from this resource or replace the content of it with "" or null, the netprofile will not be removed from the service group on the Netscaler configuration as terraform does not recognize any changes.

Example resource:

resource "citrixadc_servicegroup" "servicegroup" {
servicegroupname = "<your sg name>"
lbvserver = "<your lbvs name>"
servicetype = "<your service type>"
netprofile = "<name of netprofile>"
}

Expected behaviour
After removing the netprofile from the citrixadc_servicegroup resource it should be removed (unset) from the service group on the Netscaler configuration, but terraform responds with "no changes".

Environment:

OS: WSL (Ubuntu 20.04.6 LTS) on Windows 10
Terraform v1.4.6
Using previously-installed citrix/citrixadc v1.37.0

Thanks in advance.

**Comment by rohit-myali** [comment]
Hi @alexander-wetzling 
Thanks for raising this issue.
This is one of the drawback from the terraform plugin sdk. It doesn't detect the null or unsetting of values.

Thanks
Rohit
