### ISSUE TITLE
[FEATURE REQUEST]  Implement "citrixadc_lbaction" and "citrixadc_lbpolicy" resources

### ISSUE THREAD

**Issue by gusmb** [citrix/terraform-provider-citrixadc#1129]
# Contact us

> For any immediate issues or help , reach out to us at NetScaler-AutomationToolkit@cloud.com !

# Feature Request

As part of GSLB configurations with the Topo strategy, I need to create LB actions and LB policies, as documented here:

- https://developer-docs.netscaler.com/en-us/adc-nitro-api/current-release/configuration/lb/lbaction.html
- https://developer-docs.netscaler.com/en-us/adc-nitro-api/current-release/configuration/lb/lbpolicy.html

The corresponding Ansible modules are implemented here:
- https://netscaler.github.io/ansible-collection-netscaleradc/collections/netscaler/adc/lbaction_module.html#ansible-collections-netscaler-adc-lbaction-module
- https://netscaler.github.io/ansible-collection-netscaleradc/collections/netscaler/adc/lbpolicy_module.html#ansible-collections-netscaler-adc-lbpolicy-module

**Describe the solution you'd like**
Need to be able to manage these resources with the Terraform provider

**Describe alternatives you've considered**
Excluding this from Terraform and using Ansible To manage these resources

**Additional context**

**Comment by gusmb** [comment]
Hi @rohit-myali @sumanth-lingappa thanks for implementing lbaction and lbpolicy! The bindings are missing I think. For topology based algorithms, lbpolicy needs to be bound to the gslbvserver in order to do something with it. Is this binding resource also included in the change?

**Comment by sumanth-lingappa** [comment]
@gusmb, the bindings are not implemented.
I will re-open this PR to keep track this

**Comment by gusmb** [comment]
> @gusmb, the bindings are not implemented. I will re-open this PR to keep track this

Thank you,

I believe for GSLB it would just be the gslbvserver to lbpolicy binding:

https://developer-docs.netscaler.com/en-us/adc-nitro-api/current-release/configuration/gslb/gslbvserver_lbpolicy_binding

Similar for LB, although my use case is only GSLB for now:

https://developer-docs.netscaler.com/en-us/adc-nitro-api/current-release/configuration/lb/lbvserver_lbpolicy_binding.html

**Comment by rohit-myali** [comment]
Hello @gusmb 
Thanks for contacting us. We are now supporting `lbpolicy`, `lbaction`, `lbvserver_lbpolicy_binding` and `gslbvserver_lbpolicy_binding`.

Link to the docs:
[`lbpolicy`](https://registry.terraform.io/providers/citrix/citrixadc/latest/docs/resources/lbpolicy)
[`lbaction`](https://registry.terraform.io/providers/citrix/citrixadc/latest/docs/resources/lbaction)
[`lbvserver_lbpolicy_binding`](https://registry.terraform.io/providers/citrix/citrixadc/latest/docs/resources/lbvserver_lbpolicy_binding)
[`gslbvserver_lbpolicy_binding`.](https://registry.terraform.io/providers/citrix/citrixadc/latest/docs/resources/gslbvserver_lbpolicy_binding)

Please use the latest terraform-provider-citrixadc [v1.38.0](https://registry.terraform.io/providers/citrix/citrixadc/latest/docs)

Thanks
