### ISSUE TITLE
[FEATURE REQUEST]: Enable 5 missing specific attributes in citrixadc_appfwprofile ressource

### ISSUE THREAD

**Issue by nogiiihhmk** [citrix/terraform-provider-citrixadc#1135]
### Description

Hi Citrix,

we use attributes like
- htmlerrorstatuscode
- htmlerrorstatusmessage 
- bufferoverflowmaxtotalheaderlength
- sqlinjectiongrammar
- cmdinjectiontype

in classic wafprofile and as we are migrating classic waf config to use that in terraform as a attributes of citrixadc_appfwprofile. In CLI these setting are possible, but not in terraform as documented in https://registry.terraform.io/providers/citrix/citrixadc/latest/docs/resources/appfwprofile. Also Citrix CLI docs at https://developer-docs.netscaler.com/en-us/adc-command-reference-int/current-release/appfw/appfw-profile.html are showing these attributes.

Could you please enable usage of these attributes in citrixadc_appfwprofile terraform ressource?

Regards,
Nico

### Affected Resource(s) and/or Data Source(s)

citrixadc_appfwprofile

### Equivalent NetScaler CLI Command

htmlerrorStatusCode:
set appfw profile WAF_PROFILENAME -htmlerrorStatusCode 400

htmlerrorStatusMessage
set appfw profile WAF_PROFILENAME -htmlerrorStatusMessage "Forbidden"

bufferoverflowmaxtotalheaderlength
set appfw profile WAF_PROFILENAME -bufferoverflowmaxtotalheaderlength 1000

sqlinjectiongrammar
set appfw profile WAF_PROFILENAME -sqlinjectiongrammar "OFF"

cmdinjectiontype
set appfw profile WAF_PROFILENAME -cmdinjectiontype "CMDSplCharORKeyword"

### Potential Terraform Configuration

```terraform
resource "citrixadc_appfwprofile" "demo_appfw" {
  htmlerrorStatusCode = 400
  htmlerrorStatusMessage = "Forbidden"
  bufferoverflowmaxtotalheaderlength = 1
  sqlinjectiongrammar = "ON"
  cmdinjectiontype = "CMDSplCharANDKeyword"  
  #...
  # and all the other mandatory attributes
}
```

### References

https://developer-docs.netscaler.com/en-us/adc-command-reference-int/current-release/appfw/appfw-profile.html

**Comment by rohit-myali** [comment]
Hello @nogiiihhmk 
Thanks for raising this feature request.

We have worked on this and and it is now available in the terraform registry. Please download the latest terraform-provider-citrixadc version v1.38.0.

Link to documentation [HERE](https://registry.terraform.io/providers/citrix/citrixadc/latest/docs/resources/appfwprofile#htmlerrorstatuscode)

Thank you
