### ISSUE TITLE
lbvserver not setting `ciphers` correctly

### ISSUE THREAD

**Issue by bowersni** [citrix/terraform-provider-citrixadc#114]
I am new to using this provider within Terraform, but I am seeing odd behavior where the configuration is valid and says it is updating my SSL LB vServer with the correct cipher suite names, but I am not actually seeing it done when I login to the Web UI to check it - and my HTTPS LB endpoint is not working when there is not a cipher suite group set... any ideas?

Code:

```
resource "citrixadc_lbvserver" "netscaler_poc_lb" {
  name = "terraform_poc_lb"
  ipv46 = "x.x.x.x"
  port = 443
  servicetype = "SSL"
  lbmethod = "LEASTCONNECTION"
  sslcertkey = "cert-key-name"
  sslprofile = "ns_default_ssl_profile_secure_frontend"
  ciphers = ["Custom_CipherGroup_Name", "DEFAULT"]
}

resource "citrixadc_servicegroup" "netscaler_poc_service_group" {
  servicegroupname = "terraform_poc_service_group"
  servicetype = "HTTP"
  lbvservers = [citrixadc_lbvserver.netscaler_poc_lb.name]
  servicegroupmembers = ["x.x.x.x:80","x.x.x.x:80"]
}
```

Let me know if I can help with providing any other details. Basically the `ciphers` part seems to not be actually set, but there are 0 errors returned.

**Comment by giorgos-nikolopoulos** [comment]
Use `ciphersuites` instead of `ciphers`.

`ciphers` is applicable only in cluster deployments.

**Comment by bowersni** [comment]
Thank you @giorgos-nikolopoulos - that worked like a charm.
