### ISSUE TITLE
[Bug]: "Invalid argument [ipaddress]"

### ISSUE THREAD

**Issue by adh-cnc** [citrix/terraform-provider-citrixadc#1159]
### Terraform Core Version

1.8.3

### citrixadc Provider Version

1.38.0

### Operating system

MacOS

### Affected Resource(s)

citrixadc_hanode

### Equivalent NetScaler CLI Command

Unknown

### Expected Behavior

HA configuration should succeed.

### Actual Behavior

TF plan works and displays expected information, local node configures and then error message is displayed about the argument "ipaddress" being invalid.  Documentation reflects this is the correct argument to use.

### Relevant Error/Panic Output Snippet

```shell
Error: [ERROR] nitro-go: Failed to update resource of type hanode,  err=failed: 599 Netscaler specific error ({ "errorcode": 278, "message": "Invalid argument [ipaddress]", "severity": "ERROR" })
│ 
│   with module.configure-vpx-ha.citrixadc_hanode.vpx_primary,
│   on .terraform/modules/configure-vpx-ha/terraform/configure_ha.tf line 8, in resource "citrixadc_hanode" "vpx_primary":
│    8: resource "citrixadc_hanode" "vpx_primary" {
│ 
╵
```

### Terraform Configuration Files

```shell
resource "citrixadc_hanode" "local_node" {
  provider      = citrixadc.PRIMARY
  hanode_id     = 0
  hellointerval = 400
  deadinterval  = 30
}

resource "citrixadc_hanode" "vpx_primary" {
  hanode_id = citrixadc_hanode.local_node.hanode_id
  ipaddress = var.primary_vpx_nsip
  provider = citrixadc.PRIMARY
  depends_on = [ citrixadc_hanode.local_node ]
}

resource "citrixadc_hanode" "vpx_secondary" {
  hanode_id = 1
  ipaddress = var.secondary_vpx_nsip
  provider = citrixadc.SECONDARY
  depends_on = [ citrixadc_hanode.vpx_primary ]
}

resource "citrixadc_nsrpcnode" "vpx_primary_a" {
  ipaddress = var.primary_vpx_nsip
  password = var.vpx_rpc_node_password
  secure = "ON"
  provider = citrixadc.PRIMARY
  depends_on = [ citrixadc_hanode.primary_vpx ]
}

resource "citrixadc_nsrpcnode" "vpx_primary_b" {
  ipaddress = var.secondary_vpx_nsip
  password = var.vpx_rpc_node_password
  secure = "ON"
  provider = citrixadc.SECONDARY
  depends_on = [ citrixadc_hanode.primary_vpx ]
}

resource "citrixadc_nsrpcnode" "vpx_secondary_a" {
  ipaddress = var.secondary_vpx_nsip
  password = var.vpx_rpc_node_password
  secure = "ON"
  provider = citrixadc.SECONDARY
  depends_on = [ citrixadc_hanode.vpx_secondary ]
}

resource "citrixadc_nsrpcnode" "vpx_secondary_b" {
  ipaddress = var.primary_vpx_nsip
  password = var.vpx_rpc_node_password
  secure = "ON"
  provider = citrixadc.PRIMARY
  depends_on = [ citrixadc_hanode.vpx_secondary ]
}
``` 

### Steps to Reproduce

```shell
terraform apply
```

**Comment by rohit-myali** [comment]
Hello @adh-cnc 
Thanks for raising this request.

I see from the above configuration that:

```terraform
resource "citrixadc_hanode" "vpx_primary" {
  hanode_id  = citrixadc_hanode.local_node.hanode_id
  ipaddress  = var.primary_vpx_nsip
  provider   = citrixadc.PRIMARY
  depends_on = [citrixadc_hanode.local_node]
}
```

* In the above block, you are referring hanode_id as 0(local_node), and ipaddress as its own NSIP (var.primary_vpx_nsip), When the hanode_id is 0, you can't use ipaddress, as you are referring to same node.

***
```terraform
resource "citrixadc_hanode" "vpx_secondary" {
  hanode_id  = 1
  ipaddress  = var.secondary_vpx_nsip
  provider   = citrixadc.SECONDARY
  depends_on = [citrixadc_hanode.vpx_primary]
}
```
* From the above block, you are referring to hanode_id as 1, which is okay, but you are trying to set the ipaddress as its own NSIP (var.secondary_vpx_nsip), rather it should be primary_vpx's NSIP.

We have written a terraform-script/module to configure HA you can refer that from [HERE](https://github.com/netscaler/terraform-cloud-scripts/tree/master/on_prem/configure_on_prem_netscaler_adcs_in_high_availability/step1_configure_ha)

***

Instead, the above two block should be modified as follows:

```terraform
resource "citrixadc_hanode" "vpx_primary" {
  hanode_id  = 1
  ipaddress  = var.secondary_vpx_nsip
  provider   = citrixadc.PRIMARY
  depends_on = [citrixadc_hanode.local_node]
}

resource "citrixadc_hanode" "vpx_secondary" {
  hanode_id  = 1
  ipaddress  = var.primary_vpx_nsip
  provider   = citrixadc.SECONDARY
  depends_on = [citrixadc_hanode.vpx_primary]
}
```



Please check the above link provided to configure HA. (I am providing it again [HERE](https://github.com/netscaler/terraform-cloud-scripts/tree/master/on_prem/configure_on_prem_netscaler_adcs_in_high_availability/step1_configure_ha))
Please update me here on any progress.

Thanks
Rohit
