### ISSUE TITLE
[Bug]: Issue 1113 / 1147 is not resolved. enhancement introduces new bug

### ISSUE THREAD

**Issue by kaiAsmOne** [citrix/terraform-provider-citrixadc#1162]
### Terraform Core Version

1.5.7

### citrixadc Provider Version

1.39.0

### Operating system

Mac OS

### Affected Resource(s)

I Have a working WAF Installation with bound WAF Signatures. 
When upgrading to provider version => 1.38.0  the provider wants to replace all existing citrixadc_appfwsignatures with this change detected:

The Netscaler provider wants to change this on every run..

module.netscaler-adc-waf-fqdn_company_no.citrixadc_appfwsignatures.app_waf must be replaced
-/+ resource "citrixadc_appfwsignatures" "app_waf" {
+ action = (known after apply) # forces replacement
+ autoenablenewsignatures = (known after apply)
+ category = (known after apply)
+ enabled = (known after apply)
~ id = "waf_sig_fqdn.company.no" -> (known after apply)
+ mergedefault = (known after apply)
name = "waf_sig_fqdn.company.no"
+ ruleid = (known after apply) # forces replacement
+ sha1 = (known after apply)
+ vendortype = (known after apply)
+ xslt = (known after apply)
 (5 unchanged attributes hidden)
}

Resulting in

Error: Provider produced inconsistent result after apply
│
│ When applying changes to module.netscaler-adc-waf-fqdn_company_no.citrixadc_appfwsignatures.app_waf, provider "provider["registry.terraform.io/citrix/citrixadc"]" produced an unexpected new value: Root resource was present, but now
│ absent.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵

### Equivalent NetScaler CLI Command

https://developer-docs.netscaler.com/en-us/adc-nitro-api/13-1/configuration/appfw/appfwsignatures

### Expected Behavior

A Working citrixadc_appfwsignatures 

### Actual Behavior

Resulting in

Error: Provider produced inconsistent result after apply
│
│ When applying changes to module.netscaler-adc-waf-fqdn_company_no.citrixadc_appfwsignatures.app_waf, provider "provider["registry.terraform.io/citrix/citrixadc"]" produced an unexpected new value: Root resource was present, but now
│ absent.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵

### Terraform Configuration Files

None

### Steps to Reproduce

Configure a WAF Profile, Configure WAF Signatures. Upgrade provider to 1.38.0 and rerun existing working terraform code.
Re run terraform code and citrixadc_appfwsignatures detects a change it cannot resolve.

**Comment by rohit-myali** [comment]
Hello @kaiAsmOne 
Can you the terraform command with logs? Please paste the log file here

**Comment by kaiAsmOne** [comment]
I find it really scary to include this logfile on github. the logfile is full of confidential production data, details of all object names in my netscaler , stafefile name. The logfile is 1.6 million lines of text and i cannot risk human error in masking confidential information. 

The 1.39.0 provider does not work for WAF Work at all.. 

Is it possible for you to test this out ? 

Create a Netscaler with WAF config including signatures using the 1.37.0 provider, upgrade your config to 1.39.0 provider. 


1: Create a WAF Profile
2: Create a WAF Signature
3: Bind the signature to the WAF Profile

When upgrading to 1.39.0 Provider the following happens

1: Terraform wants to destroy the Signature to recreate it
2: This fails because the signature is already bound to the WAF Profile
3: Go into GUI, Change the WAF Profile to use another signature not used in terraform code.
4: Terraform apply now wants to change the WAF profile back to the old signature
5: Terraform wants to destroy the signature
6: Terraform cannot delete the signature because it is now bound again 

7: 

Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to module.netscaler-adc-waf-bogus_company_com.citrixadc_appfwsignatures.app_waf, provider "provider[\"registry.terraform.io/citrix/citrixadc\"]" produced an unexpected new value: Root resource was present, but now absent.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.

**Comment by kaiAsmOne** [comment]
I have implemented a standalone "citrixadc_appfwsignatures" not bound to any WAF Profile. 
Everytime i do a terraform apply the citrixadc provider wants ro replace as follows

 # module.netscaler-adc-waf-webapp_test_company_com.citrixadc_appfwsignatures.app_waf must be replaced
-/+ resource "citrixadc_appfwsignatures" "app_waf" {
      + action                  = (known after apply) # forces replacement
      + autoenablenewsignatures = (known after apply)
      + category                = (known after apply)
      + enabled                 = (known after apply)
      ~ id                      = "waf_sig_webapp-test.company.com" -> (known after apply)
      + mergedefault            = (known after apply)
        name                    = "waf_sig_webapp-test.company.com"
      + ruleid                  = (known after apply) # forces replacement
      + sha1                    = (known after apply)
      + vendortype              = (known after apply)
      + xslt                    = (known after apply)
        # (5 unchanged attributes hidden)
    }


When the terraform apply completes followed by another terraform apply it wants to do as follows again

 # module.netscaler-adc-waf-webapp_test_company_com.citrixadc_appfwsignatures.app_waf must be replaced
-/+ resource "citrixadc_appfwsignatures" "app_waf" {
      + action                  = (known after apply) # forces replacement
      + autoenablenewsignatures = (known after apply)
      + category                = (known after apply)
      + enabled                 = (known after apply)
      ~ id                      = "waf_sig_webapp-test.company.com" -> (known after apply)
      + mergedefault            = (known after apply)
        name                    = "waf_sig_webapp-test.company.com"
      + ruleid                  = (known after apply) # forces replacement
      + sha1                    = (known after apply)
      + vendortype              = (known after apply)
      + xslt                    = (known after apply)
        # (5 unchanged attributes hidden)
    }

**Comment by kaiAsmOne** [comment]
I created a WAF Signature not bound to anything. Whenever i do a terraform apply this happens:

  module.netscaler-adc-waf-webapp_test_company_com.citrixadc_appfwsignatures.app_waf must be replaced
-/+ resource "citrixadc_appfwsignatures" "app_waf" {
      + action                  = (known after apply) # forces replacement
      + autoenablenewsignatures = (known after apply)
      + category                = (known after apply)
      + enabled                 = (known after apply)
      ~ id                      = "waf_sig_webapp-test.company.com" -> (known after apply)
      + mergedefault            = (known after apply)
        name                    = "waf_sig_webapp-test.company.com"
      + ruleid                  = (known after apply) # forces replacement
      + sha1                    = (known after apply)
      + vendortype              = (known after apply)
      + xslt                    = (known after apply)
         (5 unchanged attributes hidden)
    }
.


When the terraform apply completes and i do another terraform apply the same happpens again:

  module.netscaler-adc-waf-webapp_test_company_com.citrixadc_appfwsignatures.app_waf must be replaced
-/+ resource "citrixadc_appfwsignatures" "app_waf" {
      + action                  = (known after apply) # forces replacement
      + autoenablenewsignatures = (known after apply)
      + category                = (known after apply)
      + enabled                 = (known after apply)
      ~ id                      = "waf_sig_webapp-test.company.com" -> (known after apply)
      + mergedefault            = (known after apply)
        name                    = "waf_sig_webapp-test.company.com"
      + ruleid                  = (known after apply) # forces replacement
      + sha1                    = (known after apply)
      + vendortype              = (known after apply)
      + xslt                    = (known after apply)
         (5 unchanged attributes hidden)
    }

**Comment by kaiAsmOne** [comment]
@rohit-myali : 

Hi Hope you understand that due to this bug it is not posssible to use the WAF Signatures at all by code. 
Signatures are disabled by default, you can not tune to handle False Positives per appication.

This Issue is quite urgent for those of us who needs to do Canary or blue-green deploys as required in modern cloud implementations.

**Comment by rohit-myali** [comment]
Hello @kaiAsmOne 

Thanks for waiting. 

I was able to reproduce the issue. I did work on that, we will include this in out next release.

**Comment by rohit-myali** [comment]
Hello @kaiAsmOne 

This is addressed. Please use the latest version of terraform-provider-citrixadc v1.40.1.
