### ISSUE TITLE
[Bug]:  PERSISTENCE TIMEOUT 0 not being honored - see CLOSED ISSUE #1062 - The problem exists in all providers after 1.37.0

### ISSUE THREAD

**Issue by kevinmarino** [citrix/terraform-provider-citrixadc#1169]
### Terraform Core Version

1.8.4

### citrixadc Provider Version

1.39.0

### Operating system

Windows

### Affected Resource(s)

resource "citrixadc_lbvserver" "vip" {
name = "VIP"
ipv46 = "10.10.10.10"
port = 443
servicetype = "SSL"
persistencetype = "COOKIEINSERT"
timeout = 0
}

### Equivalent NetScaler CLI Command

add lb vserver VIP SSL 10.10.10.10 443 -persistenceType COOKIEINSERT -timeout 0

### Expected Behavior

The timeout value of the persistence type CookieInsert should be set to 0.

### Actual Behavior

After applying the terraform code the cookieinsert persistence value is defaulted to 2. If you try and change the timeout value to 0 it will error out.

### Relevant Error/Panic Output Snippet

```shell
Terraform will perform the following actions:

  # module.adc-az-vpx-sandbox-1_add_lbvserver_azure_east["VST-HS-SERVICENAME-SERVICECOMPONENT-INT"].citrixadc_lbvserver.module_tf_lbvserver will be updated in-place
  ~ resource "citrixadc_lbvserver" "module_tf_lbvserver" {
        id                                 = "vst-HS-servicename-servicecomponent-INT-M1"
        name                               = "vst-HS-servicename-servicecomponent-INT-M1"
      ~ timeout                            = 2 -> 0
        # (95 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
module.adc-az-vpx-sandbox-1_add_lbvserver_azure_east["VST-HS-SERVICENAME-SERVICECOMPONENT-INT"].citrixadc_lbvserver.module_tf_lbvserver: Modifying... [id=vst-HS-servicename-servicecomponent-INT-M1]
╷
│ Error: [ERROR] netscaler-provider: Error updating lbvserver vst-HS-servicename-servicecomponent-INT-M1
│
│   with module.adc-az-vpx-sandbox-1_add_lbvserver_azure_east["VST-HS-SERVICENAME-SERVICECOMPONENT-INT"].citrixadc_lbvserver.module_tf_lbvserver,
│   on modules\add-lbvserver\main.tf line 13, in resource "citrixadc_lbvserver" "module_tf_lbvserver":
│   13: resource "citrixadc_lbvserver" "module_tf_lbvserver" {
```

### Terraform Configuration Files

terraform {
  required_providers {
    citrixadc = {
      source  = "citrix/citrixadc"
      version = "1.39.0"
    }
  }
}

provider "citrixadc" { 
  endpoint             = "https://10.10.10.5"
  username             = var.adc_admin_username
  password             = var.adc_admin_password
  insecure_skip_verify = true
}

resource "citrixadc_lbvserver" "vip" {
name = "VIP"
ipv46 = "10.10.10.10"
port = 443
servicetype = "SSL"
persistencetype = "COOKIEINSERT"
timeout = 0
}

### Steps to Reproduce

Create a LB Vserver resource with cookieinsert persistence and set a timeout value of 0. Run the apply and validate the timeout is defaulted to 2, re-run the apply to have it update to 0 and get an error.

### Important Factoids

See https://github.com/citrix/terraform-provider-citrixadc/issues/1062 - For this previous issue in 1.35.0 which was corrected in 1.37.0 build but has since become a problem again in 1.39.0 build.

### References

Previous ISSUE and CLOSED information: https://github.com/citrix/terraform-provider-citrixadc/issues/1062

**Comment by kevinmarino** [comment]
This issue still exists in 1.40.0 - Is anyone going to update the timeout value of 0 for COOKIEINSERT persistence to work with Terraform again?

**Comment by kaiAsmOne** [comment]
With the release of 1.40.1 i have finally been able to move further than 1.37.0. I noticed the above mentioned  issue came back awhile ago.

Due to this bug it is not possible to make a cookie become a session cookie. 

It would be nice to have this bug fixed because it messes up applications. 

i am amazed by the low download counters on terraform registry citrix adc provider. Netscaler is as far as i know the best product to actually provide true preauth on all applications serving both onprem, hybrid and cloud with one common solution. ZTNA is all the rave these days but most vendors are just foilware bullshit. All big enterprises are bound to be hybrid for quite a few years. i am puzzled by the lack of marketing of this product.

**Comment by kevinmarino** [comment]
Please correct the Timeout value of 0 being an acceptable value. This is necessary for configurations we use for COOKIEINSERT persistence type. You had this working in version 1.37.0 and then decided to break it in all the following versions. This is still an issue in 1.41.0. Considering you had it working I would presume this would be a simple fix.
