### ISSUE TITLE
would like to use transform

### ISSUE THREAD

**Issue by DevGumbo** [citrix/terraform-provider-citrixadc#118]
We are needing to use the transform piece in terraform to have a pipeline direct string type url for rewrite and then use that to say beginning pattern and post transform pattern.

Can i get some assistance on extending this ?

**Comment by DevGumbo** [comment]
compiled transform action and it builds in terraform but getting an error when try to apply.

`resource "citrixadc_transformaction" "mytranscformaction" {

    comment = "abc"
    cookiedomainfrom = "abc"
    cookiedomaininto = "abc"
    name = "abc"
    priority = 42
    profilename = "abc"
    requrlfrom = "from_url"
    requrlinto = "into_url"
    resurlfrom = "result_url"
    resurlinto = "resul_into_url"
    state = "ENABLED"
}
`
`# citrixadc_transformaction.mytranscformaction will be created
  + resource "citrixadc_transformaction" "mytranscformaction" {
      + comment          = "abc"
      + cookiedomainfrom = "abc"
      + cookiedomaininto = "abc"
      + id               = (known after apply)
      + name             = "abc"
      + priority         = 42
      + profilename      = "abc"
      + requrlfrom       = "abc"
      + requrlinto       = "abc"
      + resurlfrom       = "abc"
      + resurlinto       = "abc"
      + state            = "ENABLED"
    }`

`Error: [ERROR] go-nitro: Failed to create resource of type transformaction, name=abc, err=failed: 404 Not Found ({ "errorcode": 258, "message": "No such resource [name, abc]", "severity": "ERROR" })`

**Comment by giorgos-nikolopoulos** [comment]
We will need to implement this resource.

The generator scripts under `tools/` do not produce a functioning resource out of the box.
Manual intervention is needed in most cases to correct errors.

Will take this up when time permits.

**Comment by giorgos-nikolopoulos** [comment]
Fixed with #136
