### ISSUE TITLE
[FEATURE REQUEST]:  servicegroup - sslprofile support

### ISSUE THREAD

**Issue by adc-nerd** [citrix/terraform-provider-citrixadc#1186]
### Description

With SSL Default Profile enabled it's common to bind SSL-Backend-Profiles to service groups.
There's currently no sslprofilename for servicegroup ressources (like httpprofilename, tcpprofilename....)

### Affected Resource(s) and/or Data Source(s)

servicegroup

### Equivalent NetScaler CLI Command

set ssl serviceGroup my-svg -sslprofile my-backend-ssl-profile

### Potential Terraform Configuration

```terraform
resource "citrixadc_servicegroup" "my_svg" {
...
sslprofilename = "my-backend-ssl-profile"
...
}
```

### References

https://docs.netscaler.com/en-us/citrix-adc/current-release/ssl/ssl-profiles/ssl-enabling-the-default-profile.html

**Comment by HS1542** [comment]
I think you are looking at the wrong place in the documentation, sslprofile can be set on the servicegroup?
https://registry.terraform.io/providers/citrix/citrixadc/latest/docs/resources/sslservicegroup

**Comment by adc-nerd** [comment]
Thank you - that's it! To set an SSL profile for a service group, you must create an additional sslservicegroup resource. 

```terraform
resource "citrixadc_servicegroup" "tf_svg" {
...
}

resource "citrixadc_sslservicegroup" "tf_sslsvg" {
    servicegroupname = citrixadc_servicegroup.tf_svg.servicegroupname
    sslprofile = "my-ssl-backend-profile"
}
```
