### ISSUE TITLE
Please consider publishing this provider to the Terraform Registry

### ISSUE THREAD

**Issue by ivoronin** [citrix/terraform-provider-citrixadc#122]
Please consider publishing this provider to the Terraform Registry:

https://www.terraform.io/docs/registry/providers/publishing.html

**Comment by aicarmic** [comment]
👋  Hi there! We noticed this provider is on our list of community providers, however it has not yet been published to the newly-released Terraform Registry for Providers (registry.terraform.io). We'd like to invite you to get it published, since it makes using and installing it much easier for anyone using Terraform 0.13! Instructions for doing so are available [here](https://www.terraform.io/docs/registry/providers/publishing.html). Please note that we will soon be redirecting the [community listing page](https://www.terraform.io/docs/providers/type/community-index.html) to registry.terraform.io.

Thanks for your contributions and we look forward to seeing this provider listed soon!

Thanks,
Team Terraform @ HashiCorp

**Comment by davemcdonnell** [comment]
+1 for this, its so much easier when its published to registry.

**Comment by vadharm** [comment]
We are in the process of publishing in registry. Will update you soon.

**Comment by aicarmic** [comment]
Awesome news, thanks for the update @vadharm and let us know if we can do anything to help during the publishing process. I should also mention that we recently released a tool that helps automate documentation generation. Worth checking out as it may help along the way! More on this [here](https://www.terraform.io/docs/registry/providers/docs.html#generating-documentation).


Cheers,
Team Terraform

**Comment by vadharm** [comment]
Sure @aicarmic. I am working with Chriss Griggs. Will keep you posted.

**Comment by piontekdd** [comment]
Do you know how close you are to getting this published to the registry? I'm in the process of upgrading from TF 11 and would love to skip 12 and go right to 13, but we use this provider heavily and having it the registry helps a lot.

**Comment by vadharm** [comment]
Glad to see you using adc terraform provider and finding it useful. We are close, there are couple of things that needs to be resolved and we already working with Hashicorp partner team on same. Best case scenario would be one month from now to get provider listed in registry. Apologies for the hassle on installing this separately, but I assure you we are doing our best to get this in TF registry asap.

**Comment by piontekdd** [comment]
I've been struggling with getting the current provider installed as a local plugin with Terraform 13 for a couple days. Is the current provider compatible with 13 yet? that's the only thing I can think of as I have everything set up correctly.

**Comment by jantytgat** [comment]
@piontekdd how are you loading the provider right now?
I spent a day getting it to work this week, as the documentation is not complete or partly incorrect.
I'm in the process of writing a blog post about loading the provider.

I completely agree, I hope this makes it to the registry very soon!

**Comment by piontekdd** [comment]
@jantytgat I should put a pastebin or gist together for that. Not sure what platform you're on.


Example for v0.12.40 of the citrixadc for macos <fake domain> and <project>  can be anything. I used my project name
- mkdir -p $HOME/.terraform.d/plugins/<name>/citrixadc/0.12.40/darwin_amd64
- cp terraform-provider-citrixadc $HOME/.terraform.d/plugins/<fake domain>/<project>/citrixadc/0.12.40/darwin_amd64/.

you will need a versions.tf that looks something like this:

```
terraform {
  required_version = ">= 0.13"

  required_providers {
    citrixadc = {
      source = "<fake domain>/<project>/citrixadc"
      version = "0.12.40"
    }
  }
}
```

terraform init should now find and install the provider

**Comment by jantytgat** [comment]
Now that looks like how it should be. As I figured, documentation is just incomplete.
I wrote a .terraformrc file to force the lookup to a local directory. Thanks for the comment!

**Comment by tr1ck3r** [comment]
@vadharm can you please share a current ETA for the Citrix ADC provider being available in the Terraform Registry?  Thank you in advance!

**Comment by vadharm** [comment]
@tr1ck3r  - By April end we are targeting to list the provider in Terraform Registry. That's the current ETA.

**Comment by chiradeep** [comment]
This is now live https://registry.terraform.io/providers/citrix/citrixadc/latest
