### ISSUE TITLE
Binding Service to multiple VirtualServers

### ISSUE THREAD

**Issue by gstiller** [citrix/terraform-provider-citrixadc#128]
Hi,

I saw a similar issue (#5 ) what already fixed.
Can you please implement the same for service?
Or for lbvserver resource change the `servicename` parameter from String to TypeSet?
Maybe both would be the perfect solution.

Thanks in advanced

**Comment by vadharm** [comment]
Will review the request.

**Comment by giorgos-nikolopoulos** [comment]
Yes this change is feasible.

We will take it up when time permits.

**Comment by giorgos-nikolopoulos** [comment]
Fixed with #135

`resource_citrixadc_lbvserver_service_binding` has been created to allow multiple lbvservers to bind to a single service.

Do not use the `lbvserver` field of `resource_citrixadc_service` when setting bindings in this manner.
