### ISSUE TITLE
Add call for "bind policy stringmap"

### ISSUE THREAD

**Issue by jantytgat** [citrix/terraform-provider-citrixadc#130]
I want to be able to add entries to a stringmap on Citrix ADC from Terraform.

CLI Command:
bind policy stringmap <stringmap_name> <stringmap_key> <stringmap_value>

I believe in the Nitro API, it is called policystringmap_binding or policystringmappattern_binding.

Thanks!

**Comment by vadharm** [comment]
Let us review it and come back

**Comment by jantytgat** [comment]
What does that mean exactly? Do you have an estimated ETA?
I'd learn the go-language to implement it myself and donate it to Citrix, but legal isn't allowing this...

**Comment by vadharm** [comment]
We will be targeting Feb end/early march for the enhancement.

**Comment by giorgos-nikolopoulos** [comment]
Fixed with #136
