### ISSUE TITLE
Creation of citrixadc_servicegroup with 'nameserver' parameter fails.

### ISSUE THREAD

**Issue by kevgreen-ebay-com** [citrix/terraform-provider-citrixadc#132]
**Describe the bug**

It looks a lot like the provider thinks that the 'nameserver' parameter of the citrixadc_servicegroup object 'belongs' to that object where it appears to actually belong to the binding of service to servicegroup. I've taken plenty of time to isolate it down to just the presence or absence of the 'nameserver' parameter.

So for example using the provider to replicate this documentation does not work:

https://docs.citrix.com/en-us/citrix-adc/current-release/dns/service-discovery-using-dns-srv-records.html

PS. Redacted this a lot because of obvious security sensitivities.

**To Reproduce**

TF code:

> 
> resource "citrixadc_servicegroup" "cloud_thing1_svcg" {
>     servicegroupname = "cloud_thing1_svcg"
>     servicetype = "HTTP"
>     autoscale = "DNS"
>     nameserver = "10.10.10.10"
>     depends_on = [
>          citrixadc_server.cloud_thing1_srv,
>          citrixadc_lbvserver.thing2-dns-udp-cloud
>     ]
>     servicegroupmembers_by_servername = ["cloud_thing1_srv"]
>     lbvservers = [ citrixadc_lbvserver.thing1.name ]
> }

terraform apply:

citrixadc_server.cloud_thing1_srv: Modifying... [id=cloud_thing1_srv]
citrixadc_server.cloud_thing1_srv: Modifications complete after 0s [id=cloud_thing1_srv]
citrixadc_servicegroup.cloud_thing1_svcg: Creating...

Error: [ERROR] go-nitro: Failed to create resource of type servicegroup, name=cloud_thing1_svcg, err=failed: 400 Bad Request ({ "errorcode": 1093, "message": "Argument pre-requisite missing [nameServer, serverName]", "severity": "ERROR" })

  on backends_thing1.tf line 14, in resource "citrixadc_servicegroup" "cloud_thing1_svcg":
  14: resource "citrixadc_servicegroup" "cloud_thing1_svcg" {

Comment out the nameserver parameter and things are created fine, but this doesn't meet our needs because being able to specify the nameserver is essential for our purposes.

**Expected behavior**

It should work and the nameserver be applied to the binding object not the servicegroup object.

I guess the 'nameserver' element needs removing and a servicegroup-to-server binding object added where it should go instead?  It might be that the code is already trying to do this, in a non-obvious way.

Anyway, equivalent to doing this on the CLI:

bind servicegroup cloud_thing1_svcg cloud_thing1_srv -nameServer 10.10.10.10

But I can't see an existing object type in the provider to do that?

**Logs**

The logs don't seem to show anything other than the expected JSON being sent, including the 'nameserver' field when specified, which causes the error, the payload being:

'{"servicegroup": {"autoscale":"DNS","nameserver":"10.10.10.10","servicegroupname":"cloud_thing1_svcg","servicetype":"HTTP"}}'

If I send the same payload via curl I get the same error as terraform reports. I've ruled out case sensitivity being the issue.

**Environment (please complete the following information):**
 - OS: Linux
 - Provider version: 0.12.37 (and one or two earlier versions possibly).
 - Terraform version: 0.12.29
 - Citrix ADC version: NS12.1: Build 56.22.nc

**Comment by kevgreen-ebay-com** [comment]
Interesting. If I read the documentation right, it looks like the *add* action for a servicegroup does not permit the 'nameserver' parameter, but the *update* action does?

**Comment by kevgreen-ebay-com** [comment]
I seem to have managed to work around this by using curl inside a local-exec provisioner against the servicegroup_servicegroupmember_binding object on the NITRO API. That object does not exist in the terraform provider, so would be nice to have it availabhle.

**Comment by vadharm** [comment]
Appreciate the detailed analysis.Team will review and work on the fix soon.

**Comment by giorgos-nikolopoulos** [comment]
Fixed with #137

There is now and explicit resource for servicegroup and member bindings.

Using these you should be able to apply the configuration you describe in this issue.
