### ISSUE TITLE
RFE - Bind existing policies to virtual servers

### ISSUE THREAD

**Issue by jantytgat** [citrix/terraform-provider-citrixadc#141]
It is currently not possible to bind existing policies to cs/lbserver.

For example:
resource "citrixadc_responderpolicy" "rsp_redirect_binding_vserver" {
    name = "RSP_REDIRECT"
    lbvserverbinding {
        name = citrixadc_lbvserver.redirect_vserver.name
        bindpoint = "REQUEST"
        priority = 100
    }
}

This will fail if the responder policy RSP_REDIRECT already exists in the configuration.
The actual error will also indicate that you need to supply a rule for the policy, and an action.

Point is, we often have loads of policies which are being re-used on a system, so it makes no sense to create separate policies for each virtual server we wish to bind the policy to.

There should be a resource like citrixadc_responderpolicy_binding to bind an existing policy to an existing vserver.

This applies to:
- responder
- rewrite
- content-switching

Could this be added to the terraform provider?

Thank you very much!

**Comment by vadharm** [comment]
Thanks @jantytgat for bringing this into attention. Will triage and resolve this soon.

**Comment by giorgos-nikolopoulos** [comment]
Fixed with #143
Added biding resources for responder and rewrite.
Cspolicies already had independent binding resource.
