### ISSUE TITLE
policypatset/policydataset "set command not present for this resource"

### ISSUE THREAD

**Issue by kevgreen-ebay-com** [citrix/terraform-provider-citrixadc#155]
Hi,

Further to the issue where support for some of this was added, I can't seem to get either to create through terraform on Netscaler 13, always getting the same type of error (redacted a bit, obviously):

Error: [ERROR] go-nitro: Failed to create resource of type policypatset, name=patset_mypatset, err=failed: 400 Bad Request ({ "errorcode": 1074, "message": "Invalid value [set command not present for this resource]", "severity": "ERROR" })

Error: [ERROR] go-nitro: Failed to create resource of type policydataset, name=mydataset, err=failed: 400 Bad Request ({ "errorcode": 1074, "message": "Invalid value [set command not present for this resource]", "severity": "ERROR" })

I've tried provider versions 0.12.45, 0.12.44, and 0.12.43. I can't try 1.0.0 as refactoring the code to use 'adc' not 'citrixadc' isn't going to be doable quickly. Plus not sure the documentation is all updated for the new provider version so not sure I could actually do it as things stand.

I am not really sure where best to start with debugging this, any suggestions?

This particular issue is very important for us to get resolved urgently if possible please.

K.

**Comment by vadharm** [comment]
Will come back on it soon.

**Comment by giorgos-nikolopoulos** [comment]
The error you are seeing is because the policypatset with the name `patset_mypatset` already exists in the target ADC, while the local state of the terraform configuration shows that it does not.

The solution would be to delete the patset from ADC through the nscli and then apply the terraform configuration.

In general configuration that is handled by terraform should not be modified by any other means.
This ensures that the local state and remote state remain in sync.

**Comment by kevgreen-ebay-com** [comment]
Thanks for confirming, this is very likely as with a big refactor of the terraform code I'm using going on right now and 100's of the objects have moved around in the state. It's hard to tell exactly what's going on where, especially when I've had to use curl-based workarounds without terraform lifecycle functionality availble. Happy to close this down.

**Comment by vadharm** [comment]
@kevgreen-ebay-com - Can we go into call sometime next week? and discuss what all functionality you need from terraform. Please drop me an email to mayur.vadhar1@citrix.com

**Comment by kevgreen-ebay-com** [comment]
Pretty busy right now. Emailed you.

**Comment by kevgreen-ebay-com** [comment]
This can be resolved now, obviously. I found the duplicate bit and it has resolved this.
