### ISSUE TITLE
Issues with ns_license resource 

### ISSUE THREAD

**Issue by msandbu** [citrix/terraform-provider-citrixadc#160]
In the example documentation for resource citrixadc_nslicense it says that the only required parameter is the LIC file, however when I'm running Terraform plan when I have defined the lic file it says

│ Error: Missing required argument
│
│   on resources.tf line 8, in resource "citrixadc_nslicense" "tf_license":
│    8: resource "citrixadc_nslicense" "tf_license" {
│
│ The argument "ssh_host_pubkey" is required, but no definition was found.

Should it be defined as required in the docs?

**Comment by giorgos-nikolopoulos** [comment]
The `ssh_host_pubkey` is required.
We open an ssh connection to upload the license file.

I have updated the documentation to reflect that.
On the next provider release it will be uploaded to Terraform registry as  well.
