### ISSUE TITLE
Saving NS Config after TF Apply

### ISSUE THREAD

**Issue by andrewhadam** [citrix/terraform-provider-citrixadc#161]
Your documentation suggests using a script called 'ns_commit.sh' but it appears that script is no longer attached with the repo.

https://github.com/citrix/terraform-provider-citrixadc/blob/master/DOCUMENTATION.md#commiting-changes-to-citrix-adcs-persistent-store

It looks like a resource was added to enable saving so my assumption is that is now the preferred way to save a config.  Feel free to let me know if that assumption isn't correct!

**Comment by giorgos-nikolopoulos** [comment]
Yes the script was removed to be compliant with Terraform registry policy.
You are correct the resource `citrixadc_save_config` is now the recommended way to save configuration.
