### ISSUE TITLE
vpnvserver support

### ISSUE THREAD

**Issue by Dogers** [citrix/terraform-provider-citrixadc#167]
This is the last (major) piece of our missing puzzle for us to start using the provider. Are there any plans to get this feature added?

**Comment by vadharm** [comment]
vpnvserver is not in plan. I believe you will need support for all the bindings as well for vpnvserver ?- https://developer-docs.citrix.com/projects/citrix-adc-nitro-api-reference/en/latest/configuration/vpn/vpnvserver/

**Comment by Dogers** [comment]
Yeah, all the additional bits would be needed too :(

Is there any reason it's not in the plan? We primarily use ADC for XenDesktop access rather than the load balancing side of things

**Comment by vadharm** [comment]
Ideally, we want to have terraform support for every NITRO API, including vpnvserver hence its part of backlog. But can't comment on ETA.

**Comment by Dogers** [comment]
Ahh okay, when you said it's not in the plan I thought you meant it wasn't going to be done, no problem for ETA!

**Comment by kaiAsmOne** [comment]
+1

 i just abandoned the netscaler ansible modules due to the much better Azure Devops Pipeline integration with terraform vs ansible. Terraform is becoming a requirement for us pushing out ansible and custom code.

**Comment by vadharm** [comment]
@kaiAsmOne  - I believe you are familiar with https://registry.terraform.io/providers/citrix/citrixadc/latest and our recent Blue-Green solution with Azure pipelines and Terraform - https://github.com/citrix/citrix-k8s-ingress-controller/tree/master/cd/blue-green

**Comment by Dogers** [comment]
@vadharm is code contribution still closed at the moment (per the contributing guidelines) ?

**Comment by vadharm** [comment]
Yes @Dogers , not accepting code contributions.

**Comment by rohit-myali** [comment]
@Dogers 

We have added most of the `vpnvserver` resource and its related bindings. So it might help you.

https://registry.terraform.io/providers/citrix/citrixadc/latest/docs/resources/vpnvserver 
Lets us know if you need anything else or else we can close this issue.
