### ISSUE TITLE
FQDN missing from citrixadc_server

### ISSUE THREAD

**Issue by mikekuzak** [citrix/terraform-provider-citrixadc#168]
Hi,

On our ADB Citrix Netscaler I'm able to setup a server from the FQDN, instead of IP. 
![image](https://user-images.githubusercontent.com/18675587/121194113-57c9e280-c866-11eb-89fb-2718162f233e.png)

I looked at the https://registry.terraform.io/providers/citrix/citrixadc/latest/docs/resources/server
definition and I'm not sure about how to set it up. When using only name I'm getting the following error:
```
 Error: [ERROR] go-nitro: Failed to create resource of type server, name=server1.mydomain.com, err=failed: 400 Bad Request ({ "errorcode": 1095, "message": "Required argument missing [domain, IPAddress]", "severity": "ERROR" })
```

**Comment by giorgos-nikolopoulos** [comment]
There is the `domain` attribute to give the FQDN for the server.

See the example below:

```hcl
resource "citrixadc_server" "tf_server" {
    name = "tf_server"
    domain = "test.example.com"
}
```
