### ISSUE TITLE
Supported way to import existing resources?

### ISSUE THREAD

**Issue by andrewhadam** [citrix/terraform-provider-citrixadc#169]
Is there currently a supported way to import existing infrastructure?  If no, is there anything in the works that might help this process?  While we certainly could reprovision and build from scratch, it would be troublesome for some of our VPXs and I would love a way to quickly just be able to pull in a state from a VPX and then manage those pulled in objects from there.

**Comment by vadharm** [comment]
We dont have import functionality yet. This is in plan but nothing available as of today. Will update you if there is an easier way  to achieve this.

**Comment by giorgos-nikolopoulos** [comment]
Currently there are a lot of resources that support the `terraform import` operation.

You can go through the documentation to see if a resource supports importing.
