### ISSUE TITLE
filterglobal_filterpolicy_binding object missing.

### ISSUE THREAD

**Issue by kevgreen-ebay-com** [citrix/terraform-provider-citrixadc#170]
Not a biggie for us, as it's seldom used or changed, but this object type appears to be missing from the provider.

**Comment by kevgreen-ebay-com** [comment]
The priority of this just grew quite a bit, please could you consider it important now.

**Comment by vadharm** [comment]
We will plan to implement this soon.

**Comment by giorgos-nikolopoulos** [comment]
Fixed with #269
