### ISSUE TITLE
citrixadc_nsconfig_save running before other resource when running terraform destroy

### ISSUE THREAD

**Issue by BAu0002** [citrix/terraform-provider-citrixadc#179]
I'm trying to use citrixadc_nsconfig_save and encounter an issue where terraform destroy is not running last.

Example tf code using terraform 0.14.3 and terraform-provider-citrixadc 1.5.0:

local {
  csw_ns_save_timestamp = "${citrixadc_csvserver.csw.name}_${timestamp()}"
}

resource "citrixadc_csvserver" "csw" {
 name = "x"
 servicetype = "HTTP"
 port = 80
 ipv46 = "1.2.3.4"
}

resource "citrixadc_nsconfig_save" "csw_ns_save" {
    all = true
    save_on_destroy = true
    concurrent_save_ok = true
    timestamp  = local.csw_ns_save_timestamp
}

The terraform log is showing the resources being executed in the following order:
csw_ns_save 
csw

is there anyway to force terraform to run citrixadc_nsconfig_save last

**Comment by giorgos-nikolopoulos** [comment]
There is no way from inside the resource code to enforce the order of execution.

This is decided by the terraform runtime by constructing the dependency graph for the resources.

The best you can do is have a second `citrixadc_nsconfig_save` resource which the csvserver resource will depend on.
That way this second resource will run in the correct order after the csvserver on destroy.
