### ISSUE TITLE
Don't ignore all errors from NITRO

### ISSUE THREAD

**Issue by chiradeep** [citrix/terraform-provider-citrixadc#20]
Also, the SDK eats the meaning of the errors (such as 401) and prevents the underlying systems to know why something hapenned.

For example if you credentials are invalid, it will remove entries from your state file on an apply

_Originally posted by @apetitbois in https://github.com/citrix/terraform-provider-netscaler/issues/17#issuecomment-413966665_

**Comment by chiradeep** [comment]
@apetitbois if you have a PR for this, it is most welcome

**Comment by hsmade** [comment]
It's even worse, when creating ACLs fails because a priority is in use for example, the provider claims it succeeded

**Comment by giorgos-nikolopoulos** [comment]
Closing as won't fix.

This issue has been longstanding and has lost relevance.
