### ISSUE TITLE
How to handle priorities on policy bindings

### ISSUE THREAD

**Issue by frankvdbh** [citrix/terraform-provider-citrixadc#238]
It is probably caused by underlying nitro API limitation, but what makes it often hard to automate is when you have to configure unique policy binding priorities.
For example, we are working on TF module for teams to self-publish their applications, and the idea is that they can deploy the LB / SG / .. using the module but the module is adding an entry to a shared content switch and AAA vServer which is used for multiple applications. As such the TF module is not aware of other policies bound to shared object. 
For CS, we can overcome the priority issue by using string maps. 
For AAA, the issue is that the terraform logic needs to know an available priority number to bind the next policy on.. 
Ideally, the binding resource should allow some reserved words like priority = next / last and for example bind the policy at the highest priority of the existing ones + 5

**Comment by giorgos-nikolopoulos** [comment]
Unfortunately we cannot handle this enhancement in the provider.

This is a feature to be added to the ADC configuration system
