### ISSUE TITLE
HTTP_PROXY / HTTPS_PROXY settings ignored, unable to use bastion tunnels

### ISSUE THREAD

**Issue by gtfortytwo** [citrix/terraform-provider-citrixadc#254]
It appears that this provider does not respect the `HTTP_PROXY` and/or `HTTPS_PROXY` environment variables. This makes it practically unusable for us because our ADC management interfaces are nearly always on protected networks and require the use of a jump/bastion host to reach them.  The only way I've been able to communicate via this provider/client is by creating direct point-to-point port-forwarding tunnels, which is problematic for many reasons.

As best I can tell, this provider uses the [adc_nitro_go](https://github.com/citrix/adc-nitro-go/) library under the hood, and _that_ library in turn seems to use the native [GoLang http packages](https://golang.org/src/net/http/transport.go) as its client, which by default will respect and use proxy settings defined in the environment.  One actually has to configure away that functionality by customizing the Transport to disable it.

Is there some special sauce we could use to enable the native proxy support in this provider as-is?  Or would it be possible to fix the Transport customizations to use [ProxyFromEnvironment](https://pkg.go.dev/net/http#ProxyFromEnvironment) or otherwise enable this proxy support?

**Comment by gtfortytwo** [comment]
It appears the problem is ultimately in the [adc_nitro_go](https://github.com/citrix/adc-nitro-go/) library.  In [this block of code](https://github.com/citrix/adc-nitro-go/blob/a57db5c1f504b9db84b4657cf54e8199aefe1350/service/client.go#L99-L124) it creates custom Transport objects but does not pass any Proxy options, effectively disabling the proxy support.  Simply adding a `Proxy: http.ProxyFromEnvironment` parameter to each Transport creation I think would resolve the issue.

**Comment by giorgos-nikolopoulos** [comment]
Fixed with #280
