### ISSUE TITLE
Can't switch partitions

### ISSUE THREAD

**Issue by rbjoergensen** [citrix/terraform-provider-citrixadc#274]
Looking through the provider in the Terraform registry and here on GitHub I can't seem to find a way to switch partitions.
Shouldn't this be a part of the provider configuration?

https://developer-docs.citrix.com/projects/netscaler-nitro-api/en/11.1/configuration/ns/nspartition/nspartition/#switch
https://registry.terraform.io/providers/citrix/citrixadc/latest/docs

**Comment by giorgos-nikolopoulos** [comment]
Fixed with #277
