### ISSUE TITLE
Pooled Capacity Allocation causes Netscaler reboot

### ISSUE THREAD

**Issue by kaiAsmOne** [citrix/terraform-provider-citrixadc#276]
Hi, 

When trying to allocate pooled capacity Netscaler will crash on both allocation and later on state refresh .
Furthermore the terraform nscapacity & nslicense does not support the required arguments for 

1: Username and password to pass to license server (ADM Server)
2: ADM Profile to register device under

**Comment by andrewhadam** [comment]
I'm going to +1 the above post.  I noticed this exact behavior and ultimately commented out the resource I was testing with until I had time to come back to it to investigate more.

**Comment by kaiAsmOne** [comment]
It would be nice to allocate a pooled capacity license

Currently this is not possible due to above mentioned:

If you have citrixadc_nscapacity / citrixadc_nslicenseserver in your config, terraform script will time out during netscaler-reboot and furthermore it will continue to reboot the netscaler everytime you do a state refresh.

**Comment by rohit-myali** [comment]
Hello @kaiAsmOne ,
We have fixed the `nscapacity` resource and released it to terraform registry v1.28.0. 
Link to docs [here](https://registry.terraform.io/providers/citrix/citrixadc/latest/docs/resources/nscapacity)
Please test the resource from your configuration and let us know if you face any issue.
If you face no error then please close this issue.!!

Thanks,
Rohit

**Comment by kaiAsmOne** [comment]
Hi, 

I have been very busy with workloads lately. I have not had the chance to test this out until 14 days ago.
I can now completely deploy and configure a Netscaler HA cluster with more or less all services in Azure. 

(i do some work with curl since i do not want to terraform import in a pipeline)

However the license part is something i still struggle with. 

I tried with the 1.33.0 provider and it still does not work. 

My config is as follows. Maybe my code is not correct ?

resource "citrixadc_nslicenseserver" "tf_licenseserver" {
  servername = "1.2.3.4"
  port       = 27000
}

# Pooled Capacity Allocation
resource "citrixadc_nscapacity" "tf_pooled" {
  bandwidth = 1000
  unit      = "Mbps"
  edition   = "Platinum"
}
