### ISSUE TITLE
Feature Request: NTP Server Support

### ISSUE THREAD

**Issue by kaiAsmOne** [citrix/terraform-provider-citrixadc#282]
Hi, 

It would be nice to be able to configure ntp server using terraform

**Comment by rohit-myali** [comment]
Hello @kaiAsmOne .
We have `ntpserver` resources that is released in Terraform recently, you can now be able to configure `ntpserver` feature in ADC using these modules.
Here is the link to the example [here](https://github.com/citrix/terraform-provider-citrixadc/tree/master/examples/ntp/ntpserver)

I'm closing this as it is delivered.
Thanks.
