### ISSUE TITLE
Feature Request: Set SNMP Community String 

### ISSUE THREAD

**Issue by kaiAsmOne** [citrix/terraform-provider-citrixadc#283]
Hi, 

It would be nice to be able to set:
 * SNMP Community String
 * SNMP Trap Destination
 * SNMP Manager

**Comment by giorgos-nikolopoulos** [comment]
We have recently created the `nitro_resource` which can create multiple resources based on a dictionary argument.
Using this you could resolve the issues you are mentioning.

You can find the documentation of the resource [here](https://github.com/citrix/terraform-provider-citrixadc/blob/master/docs/resources/nitro_resource.md).

The workflows dictionary can be found [here](https://github.com/citrix/terraform-provider-citrixadc/blob/master/citrixadc/testdata/workflows.yaml).

Below is an example of how you could use the resource for the specific resources you need.

```hcl
resource "citrixadc_nitro_resource" "snmpmanager" {
  workflows_file = "workflows.yaml"
  workflow       = "snmpmanager"

  # The following attributes changing will trigger the update function
  attributes = {
  }

  # The following attributes changinge will trigger the delete and re create of the resource
  non_updateable_attributes = {
    ipaddress = "10.23.23.24"
    netmask   = "255.255.255.255"
  }
}

resource "citrixadc_nitro_resource" "snmpmanager2" {
  workflows_file = "workflows.yaml"
  workflow       = "snmpmanager"

  # The following attributes changing will trigger the update function
  attributes = {
    domainresolveretry   = 10
  }

  # The following attributes changinge will trigger the delete and re create of the resource
  non_updateable_attributes = {
    ipaddress = "helo1234.com"
  }
}

resource "citrixadc_nitro_resource" "snmptrap" {
  workflows_file = "workflows.yaml"
  workflow       = "snmptrap"

  # The following attributes changing will trigger the update function
  attributes = {
    destport = 164
  }

  # The following attributes changinge will trigger the delete and re create of the resource
  non_updateable_attributes = {
    trapclass = "specific"
    trapdestination = "10.22.22.33"
    version = "V3"
  }
}

resource "citrixadc_nitro_resource" "snmpcommunity" {
  workflows_file = "workflows.yaml"
  workflow       = "snmpcommunity"

  # The following attributes changinge will trigger the delete and re create of the resource
  non_updateable_attributes = {
    communityname = "custom"
    permissions = "GET_BULK"
  }
}
```

**Comment by rohit-myali** [comment]
Hello @kaiAsmOne ,
We have `snmp` resources that are released in Terraform, you can now be able to configure `snmp` feature in ADC using these modules.
Here is the link to the example [here](https://github.com/citrix/terraform-provider-citrixadc/tree/master/examples/snmp)

I'm closing this as it is delivered.
Thanks.
