### ISSUE TITLE
Feature Request: Support for adding location db

### ISSUE THREAD

**Issue by kaiAsmOne** [citrix/terraform-provider-citrixadc#286]
Hi, 

It would be nice to be able to "add locationFile "/var/netscaler/inbuilt_db/Citrix_Netscaler_InBuilt_GeoIP_DB.csv"" to Netscalers deployed and configured using  Terraform

**Comment by rohit-myali** [comment]
Hello @kaiAsmOne, We have added the resource `locationfile` in our latest release in terraform registry v1.23.1
Thanks for this ticket.
`locationfile` : https://registry.terraform.io/providers/citrix/citrixadc/latest/docs/resources/locationfile
