### ISSUE TITLE
Feature Request: Botnet signature creation / clone default signature

### ISSUE THREAD

**Issue by kaiAsmOne** [citrix/terraform-provider-citrixadc#287]
Hi, 

To be able to configure botnet feature citrixadc terraform provider lacks the abillity to clone the builtin default signatures into a new user defined signature. (You cannot bind the default signatures to a botnet profile hence its not possible to get a working config using terraform citrixadc provider as is)

It would be nice to have this implemented.

**Comment by giorgos-nikolopoulos** [comment]
User defined bot signatures have been added with #477
