### ISSUE TITLE
Feature Request: creation of authorization policy

### ISSUE THREAD

**Issue by FUCKir89** [citrix/terraform-provider-citrixadc#288]
Hi!
To be able to configure authorization, please add one more resource that adds authorization policies and binds it to lbvs, such as in CLI:

add/set authorization policy "policy_name" "rule" ALLOW/DENY
bind lb vserver "lbvs_name" -policyName "policy_name"  -priority XXX -gotoPriorityExpression END -type REQUEST

Thank you!

**Comment by rohit-myali** [comment]
Hello @FUCKir89 
We have released the Required Resource to GitHub.
You can use it to configure your ADC.

**Comment by giorgos-nikolopoulos** [comment]
Fixed with #292
