### ISSUE TITLE
Feature Request: Bot Management/Profiles: Configure the different protection methods

### ISSUE THREAD

**Issue by kaiAsmOne** [citrix/terraform-provider-citrixadc#289]
Hi, 

With citrixadc provider it is not possible to configure Bot management.

It would be nice to be able to configure : 
Bot Management Profile IP Reputation Binding
Bot Management Profile Whitelist Binding
Bot Management Profile Blacklist Binding
Bot Management Signature Rate Limit Binding
Bot Management Device Fingerprint actions
Bot Management Profile Bot Trap Binding
Bot Management Profile TPS Binding
Bot Management Profile CAPTCHA Binding
Bot Management Profile Bot Log Expression Binding
Bot Management Profile Bot Keyboard and Mouse Expression Binding

**Comment by vadharm** [comment]
This is in our roadmap.

**Comment by giorgos-nikolopoulos** [comment]
Resources have been created and published with 1.15.0 release
