### ISSUE TITLE
lbvserver: authnprofile attribute

### ISSUE THREAD

**Issue by frankvdbh** [citrix/terraform-provider-citrixadc#291]
In our tests we encounter an issue when a lbvserver resource is first defined with authentication enabled ( authentication = "ON" and authnprofile is set ) and afterwards authentication is disabled.
Terraform detects the change for the authentication attribute ON -> OFF, however the change for the authnprofile attribute is not detected. (Tried setting to "" or null )
As such when the authentication profile is being deleted, it fails because it is still in use. 

```
resource "citrixadc_lbvserver" "this" {
 name        = "TF_LB_VS_${local.entityname}_INT_HTTP"
 ipv46       = "0.0.0.0"
  lbmethod    = "ROUNDROBIN"
  port        = 0
  servicetype = "HTTP"
  authnprofile = var.authentication.enabled ? "TF_AAA_PROF_OAUTH_${local.entityname}_AzureAD" : null
  authentication = var.authentication.enabled ? "ON" : "OFF"
 }
```

**Comment by rohit-myali** [comment]
Hey @frankvdbh  
Thanks for contacting us.
Our terraform provider citrixadc is using sdkv1. Which has an inability to handle null values. You can't set "" (empty string) as well as NetScaler doesn't support it.

Thanks
Rohit
