### ISSUE TITLE
VXLAN support

### ISSUE THREAD

**Issue by raphael1688** [citrix/terraform-provider-citrixadc#345]
Hi:

I need VXLAN support, please.

Thanks!

**Comment by rohit-myali** [comment]
Hello @raphael1688 
We have Published  `VXLAN` resource in provider version 1.14.0

Let us know if you need anything else or else we can close this issue.
Thanks!

**Comment by raphael1688** [comment]
There is one config need for VXLAN is BRIDGETABLE.
EX:
add bridgetable -mac 00:00:00:00:00:00 -vxlan 100 -vtep A.B.C.D

Thanks!
