### ISSUE TITLE
Adding address records to citrixadc

### ISSUE THREAD

**Issue by BAu0002** [citrix/terraform-provider-citrixadc#384]
Hi, 
I can not see any terraform resource that allow us to add netscaler address records.  Is there any plan to add this Or am I missing something?

**Comment by giorgos-nikolopoulos** [comment]
We cover dns address records.

See [here](https://github.com/citrix/terraform-provider-citrixadc/tree/master/examples/dns/dnsaddrec) for example.

If you need some other type of address record could you specify that?

**Comment by rohit-myali** [comment]
Also find the examples the docs in our registry : https://registry.terraform.io/providers/citrix/citrixadc/latest/docs/resources/dnsaddrec

Also feel free to open tickets if any.!

Thanks
