### ISSUE TITLE
VRID and NSTIMEOUT support

### ISSUE THREAD

**Issue by raphael1688** [citrix/terraform-provider-citrixadc#458]
Hi:

Please add features to support configuring vrid/vmac and nstimeout.

Thanks!

**Comment by vadharm** [comment]
Hi @raphael1688 , 
Can we connect over email at mayur.vadhar1@citrix.com to better understand your usecases  and plan them ahead ?

**Comment by rohit-myali** [comment]
Hello @raphael1688, We have released bith `vrid` and `nstimeout` in out latest release v.1.23.1.
Thanks for raising this ticket.
Feel free to raise the tickets if any.!
`nstimeout` : https://registry.terraform.io/providers/citrix/citrixadc/latest/docs/resources/nstimeout
`vrid` : https://registry.terraform.io/providers/citrix/citrixadc/latest/docs/resources/vrid
