### ISSUE TITLE
Issue w/ New LDAP Policy Binding

### ISSUE THREAD

**Issue by andrewhadam** [citrix/terraform-provider-citrixadc#473]
I went to use the new policy binding that was released in the latest released and almost immediately stumbled upon a bug I wanted to report.  Code example is as follows:

```
main.tf -

resource "citrixadc_systemglobal_authenticationldappolicy_binding" "default_ldap_policies_bindings" {
  for_each       = var.ldap_groups
  policyname     = each.value.policy_name
  globalbindtype = "SYSTEM_GLOBAL"
  feature        = "SYSTEM"
  priority       = each.value.priority
}

variables.tf - 

variable "ldap_groups" {
  type = map(object({
    ldapaction_name = string
    policy_name     = string
    searchfilter    = string
    priority        = number
  }))
  default = {
    "test" = {
      ldapaction_name = "test_ldapact"
      policy_name     = "test_ldappol"
      searchfilter    = "(omitted)"
      priority        = 100
    }
  }
}
```

When it goes to apply, I get the following error

```
│ Error: Provider produced inconsistent result after apply
│
│ When applying changes to
│ citrixadc_systemglobal_authenticationldappolicy_binding.default_ldap_policies_bindings["test "],
│ provider "provider[\"registry.terraform.io/citrix/citrixadc\"]" produced an
│ unexpected new value: Root resource was present, but now absent.
│
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
```

It does look like if I individually target an apply, the object does get made on the Netscaler but the provider returns the above error and causes our deployment pipeline to fail.

**Comment by vadharm** [comment]
@rohit-myali  - Take a look into this.

**Comment by rohit-myali** [comment]
Hello @andrewhadam i'm not observing any error with same configuration.
Can u provide us more info regarding the error. Please provide the log file of the error.

**Comment by rohit-myali** [comment]
Hello @andrewhadam , Thanks for reaching out to us !! I don't observe any such error with the same configuration..! Can you drop us an email at [mayur.vadhar1@citrix.com](mailto:mayur.vadhar1@citrix.com), we will take it forward from there.

Thanks,
Rohit
