### ISSUE TITLE
Feature request: Proxy through ADM service

### ISSUE THREAD

**Issue by ravager-dk** [citrix/terraform-provider-citrixadc#507]
It would be awesome if we could access the ADC instances not just through on-prem ADM, but also through ADM Service in Citrix Cloud. This would allow for the push to migrate on-prem ADM to ADM service, and provide increased flexibility in cross premises deployments.

**Comment by rohit-myali** [comment]
Hey @ravager-dk  , Thanks for raising this issue.
We have terraform provider for Citrix ADM Service as well you can check the GitHub repo [here](https://github.com/citrix/terraform-provider-citrixadm). You can use this to add ADC to ADM Service.
You can manage your Citrix ADC from ADM Service.

Thanks,
Rohit
