### ISSUE TITLE
Unbind servicegroup from lb vserver 

### ISSUE THREAD

**Issue by Nitesh-vaidyanath** [citrix/terraform-provider-citrixadc#514]
Hello, 

   ` I am trying to unbind servicegroup which is already bound to lb vserver using nitro api ? Now i want use only unbind and bind from terraform. How can i unbind without importing resource to terraform ? Currently we dont have resource to ubind. `

**Comment by giorgos-nikolopoulos** [comment]
Hi to bind and unbind a servicegroup from a lbvserver you should use the `citrixadc_lbvserver_servicegroup_binding` resource.

If the binding already exists and you want to use terraform then you should import the `citrixadc_lbvserver_servicegroup_binding` resource before using it to unbind.

To unbind you just need to run `terraform destroy` on the resource
