### ISSUE TITLE
How to bind csvserver and lbvserver

### ISSUE THREAD

**Issue by jovandeginste** [citrix/terraform-provider-citrixadc#54]
I want to bind a csvserver and a lbvserver, but there is no `csvserver_lbvserver_binding` resource...

```
bind cs vserver sample_cs -lbvserver sample_lb
```

or (as I would expect it):

```tf
resource "netscaler_csvserver_lbvserver_binding" "sample_cs_sample_lb" {
  csvserver = "${netscaler_csvserver.foo.name}"
  lbvserver = "${netscaler_lbvserver.foo.name}"
}
```

**Comment by jovandeginste** [comment]
I think I miss most of the bindings. Any reason those are not provided?

**Comment by giorgos-nikolopoulos** [comment]
The way we support binding lbvservers and csvservers is through cspolicies.

You have to define a policy with the csverserver and the targetlbvserver.
For a detailed example on how to do this see [here](https://github.com/citrix/terraform-provider-netscaler/tree/master/examples/content_switch_ssl_lb_mon).

The command `bind cs vserver sample_cs -lbvserver sample_lb` is used to set the default lb vserver that will be selected when all bound cspolicies have failed to match the request.

We do not support this functionality currently.

The way this could be implemented is by adding a `default_lb_vserver` option in `netscaler_csvserver` and then do the binding in the code of the `netscaler_csvserver` resource.

A workaround to the missing default lb vserver would be to use a policy with a catch all rule and low priority.

Something like this would work, provided it has the lowest priority in the cspolicies bound to the csvserver.

```
resource "netscaler_csvserver" "csvserver1" {
  name        = "csvserver1"
  ipv46       = "192.168.11.11"
  port        = "80"
  servicetype = "HTTP"
}

resource "netscaler_lbvserver" "lbvserver1" {
  name = "lbvserver1"
  ipv46       = "10.60.2.2"
  port        = "80"
  servicetype = "HTTP"
  
}

resource "netscaler_cspolicy" "default_policy" {
  targetlbvserver = netscaler_lbvserver.lbvserver1.name
  csvserver  = netscaler_csvserver.csvserver1.name
  policyname = "defaultpolicy"
  priority   = 99
  rule       = "HTTP.REQ.IS_VALID"
}

```

**Comment by jovandeginste** [comment]
I see; we don't seem to use cspolicies. What would be the equivalent of a TCP (non-HTTP) catch-all rule?

**Comment by giorgos-nikolopoulos** [comment]
I think this expresssion would match all ipv4 TCP traffic on the client side

`CLIENT.IP.PROTOCOL.EQ(TCP)`
