### ISSUE TITLE
Provide data resources.

### ISSUE THREAD

**Issue by philof** [citrix/terraform-provider-citrixadc#571]
There are existing ADC resources in the environment which need to be managed by terraform.

Please provide data resources for ADC objects.

Example:
```hcl
data "citrixadc_server" "this" {
    name = "test_server"
}

resource "citrixadc_service" "this" {
  name = "test_server_svc"
  port = 80
  servername = data.citrixadc_server.this.name
  servicetype = "HTTP"
}
```

**Comment by giorgos-nikolopoulos** [comment]
We have recently added the generic data source `nitro_info`.
Here is an example of how to use it 
```hcl
data "citrixadc_nitro_info" "server_info" {
    workflow = yamldecode(file("../workflows/server.yaml"))
    primary_id = "tf_server"
}


output "nitro_object" {
  value = data.citrixadc_nitro_info.server_info.nitro_object
}

output "nitro_object_ipaddress" {
  value = data.citrixadc_nitro_info.server_info.nitro_object.ipaddress
}

output "nitro_object_length" {
  value = length(data.citrixadc_nitro_info.server_info.nitro_object)
}

```

Contents of the workflow map yaml file are the following;
```yaml
---
lifecycle: object_by_name
endpoint: server
bound_resource_missing_errorcode: 258
```

The basic idea behind this data source is to have a generic code base which can be applied to multiple NITRO api
endpoints without the need to compile new data sources.

The `lifecycle` attribute defines the basic flow of the read functionality, also taking into account the rest of the attributes.

You can find more examples in this [folder](https://github.com/citrix/terraform-provider-citrixadc/tree/master/examples/nitro_info)

**Comment by philof** [comment]
Thank you for the feedback.
