### ISSUE TITLE
issue initializing v0.12.3 plugin with latest examples

### ISSUE THREAD

**Issue by sherenator** [citrix/terraform-provider-citrixadc#61]
```
PS D:\code\terraform-test\terraform-provider-citrixadc\examples\content_switch_ssl_lb_mon> terraform init -plugin-dir C:\Users\username\AppData
\Roaming\terraform.d\plugins

Initializing the backend...

Initializing provider plugins...

Missing required providers.

The following provider constraints are not met by the currently-installed
provider plugins:

* citrixadc (any version)

Terraform can automatically download and install plugins to meet the given
constraints, but this step was skipped due to the use of -get-plugins=false
and/or -plugin-dir on the command line.

If automatic installation is not possible or desirable in your environment,
you may manually install plugins by downloading a suitable distribution package
and placing the plugin's executable file in one of the directories given in
by -plugin-dir on the command line, or in the following directory if custom
plugin directories are not set:
    terraform.d/plugins/windows_amd64


Error: missing provider "citrixadc"
```

**Describe the bug**
Attempting to load latest plugin with latest code version results in `Error: missing provider "citrixadc"`

**To Reproduce**

1. Download latest plugin binary
2. Check out master
3. Change directory to `content_switch_ssl_lb_ mon` example
4. Run `terraform init`

**Expected behavior**
Expect plugin to load without issue

**Environment (please complete the following information):**
 - OS: Windows
 - Terraform version 
Terraform v0.12.8
 - Citrix ADC version
v0.12.3

**Additional context**
Looking at the release notes, I think that this may be due to the `netscaler` to `citrixadc` rename. If I check out revision `21ff0f7ebef81ae3592d6b50fd76406aa1ea8bb9` and attempt to repro with latest plugin, there is no error and the plugin loads successfully.

**Comment by giorgos-nikolopoulos** [comment]
I missed the goreleaser configuration file during the rename to citrixadc.

#62 fixes the error.

The 0.12.4 release includes this fix.

**Comment by sherenator** [comment]
👍 Looks good.
