### ISSUE TITLE
Add support to set IP Address Type: Non Addressable & IP Address: 0.0.0.0 in citrixadc_lbvserver

### ISSUE THREAD

**Issue by ssdeepan** [citrix/terraform-provider-citrixadc#615]
In the resource "citrixadc_lbvserver", option to set the virtual server IP address type to non addressable is not available. Current provider version 1.17.0 does not accept "0.0.0.0" to the option ipv46. This may be related to address type of the lbvserver.

 Error: [ERROR] netscaler-provider: Error updating lbvserver

**Comment by giorgos-nikolopoulos** [comment]
You can use the "0.0.0.0" address as long as you also specify port to be "0".

If you give any other value for port you will get an error from NITRO "Operation not permitted"

Let us know if this solves your problem.

**Comment by ssdeepan** [comment]
@giorgos-nikolopoulos Setting the port to '0' resolved the problem. Thanks.
