### ISSUE TITLE
Documentation issue, example for sslcertkey resource stores cert and key in invalid location

### ISSUE THREAD

**Issue by stevenwright1** [citrix/terraform-provider-citrixadc#621]
The default path is noted within the cert and key parameters, however, using the default example path ("/var/tmp") will likely lead to data loss when the temporary data is cleared and (as noted in the parameter section) will not not sync between HA nodes.
I think we should adjust the docs to use the following example. 

resource "citrixadc_sslcertkey" "tf_sslcertkey" {
  certkey = "tf_sslcertkey"
  cert = "/nsconfig/ssl/certificate1.crt"
  key = "/nsconfig/ssl/key1.pem"
  notificationperiod = 40
  expirymonitor = "ENABLED"
}

**Comment by rohit-myali** [comment]
Hello @stevenwright1, 
Thanks for your valuable input. We have updated the docs with the most appropriate example.
Refer [here](https://github.com/citrix/terraform-provider-citrixadc/blob/master/docs/resources/sslcertkey.md) for docs.

Thanks,
Rohit
