### ISSUE TITLE
Documentation: data types and possible values

### ISSUE THREAD

**Issue by slauger** [citrix/terraform-provider-citrixadc#622]
Very often it is unclear what the accepted values for a parameter are. Is it `true` (as boolean), `"true"` (as string), `"ON"`, `"ENABLED"`  - or maybe something else?

<img width="673" alt="Bildschirmfoto 2022-07-19 um 10 47 59" src="https://user-images.githubusercontent.com/8333300/179709227-60631e2d-d2f4-4398-a42e-5552b6288b9c.png">

Also the error / the API response does not help much in this case.

```
│ Error: [ERROR] nitro-go: Failed to create resource of type vpnsessionaction, name=tf_sessionaction_xenmobile_os, err=failed: 400 Bad Request ({ "errorcode": 1097, "message": "Invalid argument value [OFF]", "severity": "ERROR" })
│ 
│   with module.citrix_adc.citrixadc_vpnsessionaction.vpnsessionaction["xenmobile_os"],
│   on ../../modules/citrix_adc/gateway.tf line 72, in resource "citrixadc_vpnsessionaction" "vpnsessionaction":
│   72: resource "citrixadc_vpnsessionaction" "vpnsessionaction" {
```

Maybe the datatype and the possible values can be added to the documentation by default.

**Comment by rohit-myali** [comment]
The Attribute `securebrowse` will accept the values : `ENABLED`, `DISABLED`

For the information about the value that the attribute supports you can refer the documentation [here](https://developer-docs.citrix.com/projects/citrix-adc-nitro-api-reference/en/latest/configuration/configuration/)

**Comment by slauger** [comment]
> The Attribute `securebrowse` will accept the values : `ENABLED`, `DISABLED` We will try to enhance our documentation. For the information about the value that the attribute supports you can refer the documentation [here](https://developer-docs.citrix.com/projects/citrix-adc-nitro-api-reference/en/latest/configuration/configuration/)

I know which parameters the `securebrowse` attribute accepts. This was just an example. Also i'm aware of the Citrix ADC NITRO docs and i'm working with the NITRO REST since years.
But maybe this is not the case for everyone and and I could imagine that it would be much easier for a newbie to work with the module if the documentation would be a bit more detailed.

Thanks!

**Comment by vadharm** [comment]
Thank you Simon, we will consider this enhancement during our planning. -"Datatype and the possible values can be added to the documentation by default."
