### ISSUE TITLE
Feature request: NTP support

### ISSUE THREAD

**Issue by stevenwright1** [citrix/terraform-provider-citrixadc#623]
There doesn't appear to be a way to configure NTP using Terraform
"add ntp server pool.ntp.org
enable ntp sync"

**Comment by rohit-myali** [comment]
Hello @stevenwright1 , Please find the required `ntpserver` and `ntpsync` in our latest terraform release v1.23.1.
Thanks for this ticket and feel free to raise tickets if any..!
link to documentation :
 `ntpserver` : https://registry.terraform.io/providers/citrix/citrixadc/latest/docs/resources/ntpserver
`ntpsync` : https://registry.terraform.io/providers/citrix/citrixadc/latest/docs/resources/ntpsync
