### ISSUE TITLE
Feature request: Create HA configuration and query HA node details

### ISSUE THREAD

**Issue by stevenwright1** [citrix/terraform-provider-citrixadc#624]
I'd like to create an HA pair using Terraform but, it doesn't appear to be possible yet. 

Ideally, I would also like to query the members of the HA pair so that I know the IP address of the primary/secondary node to set a custom RPC node password (I can change the password now, I'm not sure how to request the secondary node's IP to make that change).

**Comment by rohit-myali** [comment]
Hello @stevenwright1 ,
Thanks for raising this ticket.
Please find the link to the documentation [here](https://github.com/citrix/terraform-provider-citrixadc/blob/master/docs/data-sources/hanode.md)

Thanks,
Rohit
