### ISSUE TITLE
Feature request: HA node configuration options

### ISSUE THREAD

**Issue by stevenwright1** [citrix/terraform-provider-citrixadc#625]
I would like to set to enable HA failsafe mode using Terraform. The use case is to ensure that the last HA node continues to provide try and service if both nodes in the pair become unhealthy (for example, if one interface on the last node fails, it should continue to try and provide service on its remaining interfaces).

The equivalent CLI command that I would like to execute using Terraform is:
set HA node -failSafe ON

Thanks

**Comment by stevenwright1** [comment]
I've changed the title to include other HA node options. 

Please can we also have the option to restrict the maximum number of HA failovers? 
After a certain number of repeat failovers in a period, there will come a point where I want them to stop and the ADC to attempt to provide whatever service it can.
set ha node -maxFlips 3
set ha node -maxFlipTime 1200

**Comment by rohit-myali** [comment]
Hello @stevenwright1
We have added a resource `hanode`, which is also released in the terraform registry v1.23.1.
Using this resource you can do the above operations.
link to Docs : https://registry.terraform.io/providers/citrix/citrixadc/latest/docs/resources/hanode

Thanks,
Rohit
