### ISSUE TITLE
Feature request: cltTimeout parameter when adding LB vServers

### ISSUE THREAD

**Issue by stevenwright1** [citrix/terraform-provider-citrixadc#626]
I can't find the ctlTimeout parameter within our docs for creating an LB vServer, please could we implement it?
https://registry.terraform.io/providers/citrix/citrixadc/latest/docs/resources/lbvserver

Load Balancing virtual server cltTimeout parameter specifies the time in seconds that a connection from a client to a Load Balancing virtual server must be idle, before the appliance closes the connection.

add lb virtual server [details] -cltTimeout 120

**Comment by giorgos-nikolopoulos** [comment]
I think you misspelled the attribute. It's `clttimeout` not `ctltimeout`
