### ISSUE TITLE
Feature request: SNMP configuration

### ISSUE THREAD

**Issue by stevenwright1** [citrix/terraform-provider-citrixadc#631]
Please, could we add the capability to confirm SNMP? 
At a minimum, I hope to set an SNMPv2 manager and community. Ideally, I would also like to create SNMPv3 users. Also, traps and alarms.

set snmp manager <managerip>
add snmp community <communityName> <permissions>

add snmp user <name> -group <string> [-authType ( MD5 | SHA ) {-authPasswd } [-privType ( DES | AES ) {-privPasswd }]]

**Comment by rohit-myali** [comment]
Hello @stevenwright1, We have `snmp` resources that are released in Terraform, you can now be able to configure `snmp` feature in ADC using these modules.
Here is the link to example [here](https://github.com/citrix/terraform-provider-citrixadc/tree/master/examples/snmp)

Thanks.
