### ISSUE TITLE
Issue: multiple resource blocks don't merge for citrixadc_nsparam

### ISSUE THREAD

**Issue by stevenwright1** [citrix/terraform-provider-citrixadc#632]
I have two resource blocks for "citrixadc_nsparam" in my resource files. The first sets the timezone and the secodn cookieversion. The two produce an error rather than merging.

_This works fine:_
resource "citrixadc_nsparam" "tf_nsparam_single_block" {
  cookieversion = "1"
  timezone      = "coordinateduniversaltime"
}

_This fails:_
resource "citrixadc_nsparam" "tf_nsparam_time" {
  timezone      = "coordinateduniversaltime"
}

resource "citrixadc_nsparam" "tf_nsparam_cookie" {
  cookieversion = "1"
}

_Here is the error produced on failure:_
│ Error: [ERROR] nitro-go: Failed to update resource of type nsparam,  err=failed: 400 Bad Request ({ "errorcode": 1105, "message": "Ambiguous argument value []", "severity": "ERROR" })
│ 
│   with citrixadc_nsparam.tf_nsparam_time,
│   on resources.tf line 62, in resource "citrixadc_nsparam" "tf_nsparam_time":
│   62: resource "citrixadc_nsparam" "tf_nsparam_time" {
│

**Comment by rohit-myali** [comment]
Hello @stevenwright1 , Thanks for raising this issue. We have updated the resource `nsparam`  and it will be released to Terraform Registry in our next release. 

Thanks,
Rohit
