### ISSUE TITLE
Issue: Optional arguments in "citrixadc_nsip" are non-optional

### ISSUE THREAD

**Issue by stevenwright1** [citrix/terraform-provider-citrixadc#633]
I want to set the NSIP of my ADC to only allow secure (https) connections to the GUI.
The "ipaddress" and "netmask" arguments are listed as optional.

_This works:_
resource "citrixadc_nsip" "tf_nsip" {
  ipaddress = "192.168.9.10"
  netmask   = "255.255.0.0"
  gui       = "SECUREONLY"
}

_This fails:_
resource "citrixadc_nsip" "tf_nsip" {
  gui       = "SECUREONLY"
}

_The errors produced are:_
│ Error: [ERROR] nitro-go: Failed to create resource of type nsip, name=tf-nsip-20220720111243324700000002, err=failed: 400 Bad Request ({ "errorcode": 1110, "message": "Invalid IP address [tf-nsip-20220720111243324700000002]", "severity": "ERROR" })
│ Error: [ERROR] nitro-go: Failed to create resource of type nsip, name=192.168.9.10, err=failed: 400 Bad Request ({ "errorcode": 1095, "message": "Required argument missing [netmask]", "severity": "ERROR" })

**Comment by rohit-myali** [comment]
Hello @stevenwright1, Thanks for the input...!
We have fixed this and it will be released in our next release Soon..!!
Thanks..!

**Comment by rohit-myali** [comment]
Hello @stevenwright1 , We have fixed this..!
Thanks..!

**Comment by rohit-myali** [comment]
Hello @stevenwright1, We have updated the documentation and fixed the required attributes.
Please fine the documentation [here](https://registry.terraform.io/providers/citrix/citrixadc/latest/docs/resources/nsip)
