### ISSUE TITLE
Feature request: Add name server to ADC (for ADC to resolve FQDNs)

### ISSUE THREAD

**Issue by stevenwright1** [citrix/terraform-provider-citrixadc#635]
I usually create two LB vServers for UDP and TCP DNS requests and then add them for local DNS resolution. I can create the vServers using Terraform but, I can't add the name servers to the ADC.

add lb virtual server DNS_UDP DNS 0.0.0.0 0 -persistenceType NONE -cltTimeout 120
add lb virtual server DNS_TCP DNS_TCP 0.0.0.0 0 -persistenceType NONE -cltTimeout 120

add dns nameServer DNS_UDP -type UDP
add dns nameServer DNS_TCP -type TCP

**Comment by giorgos-nikolopoulos** [comment]
The dnsnameserver resource already exists with the provider.
See [here](https://github.com/citrix/terraform-provider-citrixadc/tree/master/examples/dns/dnsnameserver) for an example
