### ISSUE TITLE
Feature request: System parameter

### ISSUE THREAD

**Issue by stevenwright1** [citrix/terraform-provider-citrixadc#646]
I would like to set the command prompt using
"set system parameter -promptString %u@%h-%s"

I would also like to set the default user timeout, please.
set system parameter -timeout 900

**Comment by rohit-myali** [comment]
Hello @stevenwright1.
We have implemented the resource `systemparamater`. You can now use this resource to set the system parameter.
You can find the documentation [here](https://registry.terraform.io/providers/citrix/citrixadc/latest/docs/resources/systemparameter)
You can find the example for this resource [here](https://github.com/citrix/terraform-provider-citrixadc/tree/master/examples/system/systemparameter)

Thanks..!
