### ISSUE TITLE
New Resource: citrixadc_cmpglobal_binding

### ISSUE THREAD

**Issue by brittandeyoung** [citrix/terraform-provider-citrixadc#650]
As a developer I would like to be able to manage global cmp policy bindings with terraform.

Example Terraform config:
```terraform
resource "citrixadc_cmppolicy" "tf_cmppolicy" {
    name = "tf_cmppolicy"
    rule = "HTTP.RES.HEADER(\"Content-Type\").CONTAINS(\"text\")"
    resaction = "COMPRESS"
}

resource "citrixadc_cmpglobal_binding" "tf_cmpglobal_binding" {
    policyname = citrixadc_cmppolicy.tf_cmppolicy.name
    priority = 100
}
```

**Comment by vadharm** [comment]
Hi @brittandeyoung ,  
Currently we are not accepting any 3rd party contributions.We will address above usecase in our upcoming engineering cycle.
Would you be available for a quick call where we can understand any new requirements you have so we can plan to address that in upcoming engineering cycle ? Please drop us an email at mayur.vadhar1@citrix.com
Best,
Mayur

**Comment by rohit-myali** [comment]
Hello @brittandeyoung , We have `cmpglobal_cmppolicy_binding` resource released in Terraform recently, you can now be able to use it to configure ADC.
Please find the link to the example [here](https://github.com/citrix/terraform-provider-citrixadc/tree/master/examples/cmp/cmpglobal_cmppolicy_binding)

I'm closing this as it is delivered.
Thanks.
