### ISSUE TITLE
Issue: citrixadc_dnsnameserver provider complains when adding two name servers

### ISSUE THREAD

**Issue by stevenwright1** [citrix/terraform-provider-citrixadc#662]
Resources.tf contains:

resource "citrixadc_dnsnameserver" "dnsnameserver_UDP" {
  dnsvservername = "DNS_UDP"
  state          = "ENABLED"
  type           = "UDP"
}

resource "citrixadc_dnsnameserver" "dnsnameserver_TCP" {
  dnsvservername = "DNS_TCP"
  state          = "ENABLED"
  type           = "TCP"
}

Running terraform apply produces:
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to citrixadc_dnsnameserver.dnsnameserver_TCP, provider
│ "provider[\"registry.terraform.io/citrix/citrixadc\"]" produced an unexpected new value: Root resource was present, but now
│ absent.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵

The resultant Citrix ADC configuration appears to be correct.
> sh dns nameServer
1)	 DNS_UDP  -  State: UP 	Protocol: UDP
2)	 DNS_TCP  -  State: UP 	Protocol: TCP
 Done

When I next run Terraform apply it tries to add the (existing) DNS_TCP name server again.
│ Error: [ERROR] nitro-go: Failed to create resource of type dnsnameserver, name=DNS_TCP, err=failed: 400 Bad Request ({ "errorcode": 1074, "message": "Invalid value [dnsVserverName, value differs from existing entity and it cant be updated.]", "severity": "ERROR" })
│ 
│   with citrixadc_dnsnameserver.dnsnameserver_TCP,
│   on resources.tf line 252, in resource "citrixadc_dnsnameserver" "dnsnameserver_TCP":
│  252: resource "citrixadc_dnsnameserver" "dnsnameserver_TCP" {
│

**Comment by rohit-myali** [comment]
Gave the resolution to use `depends_on` wherever necessary.!
