### ISSUE TITLE
Issue: auditsyslogpolicy global binding not working

### ISSUE THREAD

**Issue by n0m4x** [citrix/terraform-provider-citrixadc#669]
I've tried the auditsyslogaction and auditsyslogpolicy out of the documentation but it failed with a "No such policy exists"

```
resource "citrixadc_auditsyslogaction" "tf_syslogaction" {
    name = "tf_syslogaction"
    serverip = "10.78.60.33"
    serverport = 514
    loglevel = [
        "ERROR",
        "NOTICE",
    ]
}

resource "citrixadc_auditsyslogpolicy" "tf_auditsyslogpolicy" {
    name = "tf_auditsyslogpolicy"
    rule = "ns_true"
    action = "tf_syslogaction"

    globalbinding {
        priority = 120
        feature = "SYSTEM"
        globalbindtype = "SYSTEM_GLOBAL"
    }
}

```
│ Error: [ERROR] nitro-go: Failed to update resource of type systemglobal_auditsyslogpolicy_binding,  err=failed: 404 Not Found ({ "errorcode": 2054, "message": "No such policy exists", "severity": "ERROR" })

**Comment by rohit-myali** [comment]
As I see in the error message, were you trying to update the Resource? 
Can you provide more context to this error?

**Comment by rohit-myali** [comment]
Hello @n0m4x, I guess you should include the `depends_on` argument in the second resource block.
```
depends_on = [
    citrixadc_auditsyslogaction.tf_syslogaction
  ]
```
```hcl

resource "citrixadc_auditsyslogaction" "tf_syslogaction" {
  name       = "tf_syslogaction"
  serverip   = "10.78.60.33"
  serverport = 514
  loglevel = [
    "ERROR",
    "NOTICE",
  ]
}

resource "citrixadc_auditsyslogpolicy" "tf_auditsyslogpolicy" {
  name   = "tf_auditsyslogpolicy"
  rule   = "ns_true"
  action = "tf_syslogaction"

  globalbinding {
    priority       = 120
    feature        = "SYSTEM"
    globalbindtype = "SYSTEM_GLOBAL"
  }
  depends_on = [
    citrixadc_auditsyslogaction.tf_syslogaction
  ]
}
```


Please check the above configuration and update us if that works..!
Thanks,
Rohit

**Comment by n0m4x** [comment]
Hi Rohit!

I'm so sorry for my late response! After my vacation I forgot to update this issue... 

It works with the depends_on argument! Thank you so much!!! 
It should also be changed in the documentation for the next users (:
