### ISSUE TITLE
Managing nsip resource

### ISSUE THREAD

**Issue by davemcdonnell** [citrix/terraform-provider-citrixadc#70]
Hi,

Is there planned support for managing nsip resources?

I'm looking at replacing some puppetlabs-netscaler code and I have a requirement to manage HOSTROUTE injection and OSPF metrics.

I cant see any code or examples that support this.

Cheers,
Dave

**Comment by giorgos-nikolopoulos** [comment]
No currently there is no support for applying nsip configuration.

**Comment by giorgos-nikolopoulos** [comment]
Fixed with #74
