### ISSUE TITLE
Terraform Provider Development Program - Initial review

### ISSUE THREAD

**Issue by cgriggs01** [citrix/terraform-provider-citrixadc#72]
I’ve taken a look at the provider here and would like to say great work so far! I do have feedback outlined below that I’d like to see addressed before we move on to the next steps. I’m opening this issues as a sort of checklist for tracking items and discussion. If it works better for you, this changes can be added to a separate branch if any changes conflict with your current build process.  The review was done on the develop branch at git commit [ba32e8b](https://github.com/citrix/terraform-provider-citrixadc/commit/ba32e8b77230448d6dda24fee5084370b9aa61ae) 

- [x] Within the tools/ directory it looks like you have an addition provider build for Netscaler, is this code used by the provider? It not, it should be removed from the repository. 

- [x] The provider should use Go Modules for the vending of required code dependancies, as well, all dependancies should be checked into the vendor directory, so that it can be built without fetching dependancies. 

- [x] Since the provider is build and released from inside our TeamCIty server, there is a specific GNUmakefile that must be used, feel free to copy the [GitHub provider makefile](https://github.com/terraform-providers/terraform-provider-github/blob/master/GNUmakefile) and will just have to update the variable on line 4 to PKG_NAME=PROVIDER_NAME

- [x] Scripts: There are a three bash scripts that are used in the provider build and release workflow, the [GitHub provider](https://github.com/terraform-providers/terraform-provider-github/tree/master/scripts) has the current used scripts. Can you add the changelog-links.sh, gogetcookie.sh scripts and remove the errcheck.sh file. 

- [x] One of our Terraform Ecosystem engineers built a linter to help align coding best practices for providers. You should use it along with your development. https://github.com/bflad/tfproviderlint

- [x] Each Terraform provider must have a CHANGELOG that is updated during reach release. Since the changeling is updated by a bot during the release it must be in a certain format. With the [AWS provider changelog](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md) as an example, the version of the next release should be tagged as “1.0.0 (Unreleased)” and will then be updated with a date by the release-bot. 

- [x] I see you’ve had this repository under an Apache license, currently all official Terraform provider use a [Mozilla Public License 2.0](https://www.mozilla.org/en-US/MPL/2.0/) within each repo, could you make this update to the repository? 

- [x] There is a standard README.md for of the official provider, see [Null provider README.md](https://github.com/terraform-providers/terraform-provider-null/blob/master/README.md)

- [x] The resource file naming convention is as follows, `resource_providername_resource_name.go` which means the file `resource_cspolicy.go` should be named `resource_citrixadc_cspolicy.go` and its corresponding acceptance test should be named `resource_citrixadc_cspolicy_test.go` , this should be follows across all resource files. 

- [x]  All providers in the terraform-providers/ GitHub org have a TravisCI check run on each PR that is opened. Can you please add a .travis.yaml file to make the [standard configuration](https://github.com/terraform-providers/terraform-provider-null/blob/master/.travis.yml)

- [x] There are a few files that won’t be needed once the provider is under the terraform-providers/ organization; .circleci, ISSUE_TEMPLATE,  Gopkg.lock, Gopkg.toml, ns_commit.sh

Let me know if you have any questions, I look forward to releasing this provider with you'll!

Best,
Chris

**Comment by giorgos-nikolopoulos** [comment]
Thank you @cgriggs01 for your feedback

I will be addressing the points you mention and let you know if I need any additional clarifications.

**Comment by giorgos-nikolopoulos** [comment]
@cgriggs01 

I have implemented the changes requested in this [branch](https://github.com/citrix/terraform-provider-citrixadc/tree/terraform_conformity).

**Comment by cgriggs01** [comment]
Hey @giorgos-nikolopoulos, 

You will need to build website documentation in a website/ directory that will be hosted on [Terraform.io](Terraform.io/docs/providers/index.html) for each resource and data source, these are all written in Markdown with a ruby layout file for the sidebar formatting.  Check out the [Github provider](https://github.com/terraform-providers/terraform-provider-github) website docs as a good example.

**Comment by cgriggs01** [comment]
Hey @giorgos-nikolopoulos,

Hope all is well. Any update on the website documentation?

We'd love to get this provider released so that our mutual customers can benefit from accesses the provider with Terraform init.

Let know if you have any questions.
Best
Chris

**Comment by jantytgat** [comment]
Ping!

**Comment by vadharm** [comment]
Citrix ADC provider is now live in TF Registry - https://registry.terraform.io/providers/citrix/citrixadc/latest !
