### ISSUE TITLE
CitrixADC provider - Supplied URL does not have a HTTP/HTTPS scheme error

### ISSUE THREAD

**Issue by hardjopranoto** [citrix/terraform-provider-citrixadc#76]
**Describe the bug**
I receive the following error when I'm doing a terraform plan command. 

$ terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.
------------------------------------------------------------------------

Error: Supplied URL  does not have a HTTP/HTTPS scheme

  on provider.tf line 3, in provider "citrixadc":
   3: provider "citrixadc" {                      

This is the content of my provider.tf file:

provider "citrixadc" {
  username = var.admin_username
  password = var.admin_password
  endpoint = "http://${azurerm_public_ip.mgmtpip.ip_address}"
}  

However, azurerm_public_ip.mgmtpip.ip_address is obviously not set yet until the netscaler is created. 

I would like to be able to set the endpoint URL to be set as dynamic later down the stage rather than setting it up as static url at the beginning.

Is it possible to do this?

**Environment (please complete the following information):**
 - OS: Ubuntu
 - Terraform version v0.12.21

**Comment by chiradeep** [comment]
Apparently not
https://www.terraform.io/docs/configuration/providers.html#provider-configuration 

> The configuration arguments defined by the provider may be assigned using expressions, which can for example allow them to be parameterized by input variables. However, since provider configurations must be evaluated in order to perform any resource type action, provider configurations may refer only to values that are known before the configuration is applied. In particular, avoid referring to attributes exported by other resources unless their values are specified directly in the configuration.

**Comment by hardjopranoto** [comment]
thx chiradeep... looks like i have to split my terraform script..
