### ISSUE TITLE
Feature Request: Application Firewall Profile resource update

### ISSUE THREAD

**Issue by bak-minsu** [citrix/terraform-provider-citrixadc#801]
I've found that the citrixadc_appfwprofile resource is missing certain settings we were currently using in our environment, such as postbodylimitaction, bufferoverflowmaxquerylength, cookiehijackingaction, infercontenttypexmlpayloadaction, and cmdinjectionaction. 

I've used the following API docs to make sure that these are valid fields that could be sent using the Nitro API.
https://developer-docs.citrix.com/projects/netscaler-nitro-api/en/latest/configuration/appfw/appfwprofile/

I'd like to request these be added to the resource

**Comment by vadharm** [comment]
Hi @bak-minsu , 

Thanks for reaching out ! Sure , can you you please send us email at mayur.vadhar1@citrix.com , we can discuss the usecases and plan for it over the email. 

Best,
Mayur

**Comment by bak-minsu** [comment]
@vadharm I've sent an email, thank you.

**Comment by sumanth-lingappa** [comment]
@bak-minsu Please find the latest release v1.23.1 in terraform registry which contains the missed attributes of appfwprofile.
Feel free to log any concerns in anything in general.
Thank you for opening the ticket.

https://registry.terraform.io/providers/citrix/citrixadc/latest/docs/resources/appfwprofile
