### ISSUE TITLE
Issue: citrixadc_sslservicegroup_sslciphersuite_binding documented but not implemented

### ISSUE THREAD

**Issue by MaxLeimgruber** [citrix/terraform-provider-citrixadc#888]
citrixadc_sslservicegroup_sslciphersuite_binding is documented (terraform-provider-citrixadc/blob/master/docs/resources/sslservicegroup_sslciphersuite_binding.md) however implementation seems to be missing.

No search results found in repo, except the above mentioned. Execution with newest adc provider (1.23.1) fails:
The provider citrix/citrixadc does not support resource type "citrixadc_sslservicegroup_sslciphersuite_binding".
Could you please implement? Thanks!

**Comment by rohit-myali** [comment]
Hello @MaxLeimgruber , thanks for letting us know. Yes, It is missing from the list of resources. 
Can you provide the equivalent CLI command for which you want to have terraform scripts for our internal help.

Thanks,
Rohit

**Comment by MaxLeimgruber** [comment]
Hello Rohit, 
thank you for your answer. 

The requirement is quite simple: 
We would like to have a way to unbind and bind ciphergroups to load balancing servicegroups. 
The goal is to only have custom cipher group bound to servicegroup (so no DEFAULT_BACKEND bound) without using custom ssl profiles on servicegroup.

CLI equivalent would be:

bind ssl serviceGroup <lb_svg_name> -cipherName <custom_cipher_group>
unbind ssl serviceGroup <lb_svg_name> -cipherName DEFAULT_BACKEND

Thanks and regards,
Max

**Comment by vadharm** [comment]
Hi @MaxLeimgruber , 
Thanks for reaching out ! Can you drop us email at mayur.vadhar1@citrix.com , we will take it forward from there.

Best,
Mayur

**Comment by rohit-myali** [comment]
Hello @MaxLeimgruber, Thanks for reaching out to us! We have released the resource `sslservicegroup_sslciphersuite_binding`.

Check [here](https://registry.terraform.io/providers/citrix/citrixadc/latest/docs/resources/sslservicegroup_sslciphersuite_binding) for example and documentation.

Thanks,
Rohit
