### ISSUE TITLE
[BUG] citrixadc_sslvserver_ecccurve_binding not working as expected

### ISSUE THREAD

**Issue by MaxLeimgruber** [citrix/terraform-provider-citrixadc#889]
The resource citrixadc_sslvserver_ecccurve_binding doesn´t change ECC curved bound to sslvserver.  

```hcl
resource "citrixadc_sslvserver_ecccurve_binding" "sslvserver_ecccurve_binding" {
  ecccurvename = "P_224"
  vservername =  "cs_vs_app1.com"
}
```
Terraform plan has an output such as:
```hcl

  # module.csvserver.citrixadc_sslvserver_ecccurve_binding.sslvserver_ecccurve_binding["cs_vs_app1.com"] will be created
  + resource "citrixadc_sslvserver_ecccurve_binding" "sslvserver_ecccurve_binding" {
      + ecccurvename = "P_224"
      + id           = (known after apply)
      + vservername  = "cs_vs_app1.com"
    }
```

However it doesnt affect binding of ecccurves on said ssl vserver. Terraform log (if TF_LOG=debug) shows no error.
No matter what curve is specified above, all 4 default curves stay bound on vserver.

Apart from adc configuration not being deployed, why isnt ecccurvename defined as a list like in 
"sslprofile_sslcertkey_binding"? Example how it could look like: 

```hcl
resource "citrixadc_sslvserver_ecccurve_binding" "sslvserver_ecccurve_binding" {
  ecccurvenames = ["P_256","P_384"]
  vservername =  citrixadc_lbvserver.tf_sslvserver.name
}
```
Thanks a lot!

**Comment by rohit-myali** [comment]
Hello @MaxLeimgruber ,
Can you please specify your ADC version as well as also the terraform provider CitrixADC version.!

**Comment by rohit-myali** [comment]
I didn't observe any errors while dealing with this resource. Please raise the issue if any..!
