### ISSUE TITLE
lbvserver should not  be required parameter in citrixadc_service

### ISSUE THREAD

**Issue by deniszh** [citrix/terraform-provider-citrixadc#91]
**Describe the bug**
`lbvserver` property should not  be required parameter in `citrixadc_service`. 
Currently I'm getting `The argument "lbvserver" is required, but no definition was found` error.

**To Reproduce**
Try to create `citrixadc_service` resource without `lbvserver` parameter.

**Expected behavior**
You should be able to create service without binding it to lbvserver, as you can do in cli:
```
add lb vserver <name> <serviceType> <ip> <port>
```

**Additional context**
https://github.com/citrix/terraform-provider-citrixadc/blob/b6f61952dc82d3ad309715de8f05fa9b06a0b6e9/citrixadc/resource_citrixadc_service.go#L294

**Comment by deniszh** [comment]
I hope assigning done automatically... I didn't assign anyone specifically.

**Comment by deniszh** [comment]
Could I kindly ask for any updates?

**Comment by giorgos-nikolopoulos** [comment]
Yes it seems that this is an error.
It should be possible to create a service without an lbvserver.

It will require some testing since the commit that introduced this change is quite old ( from 2016 ).

Currently there are some higher priority tasks.
We will fix this as soon as we can.

**Comment by tomreeb** [comment]
👍

**Comment by giorgos-nikolopoulos** [comment]
Fixed with #135

`resource_citrixadc_lbvserver_service_binding` has also been added to allow for binding multiple lbvservers to a single service.
