### ISSUE TITLE
[Feature Request] vpnvserver and sslprofile binding

### ISSUE THREAD

**Issue by nicohoffmannhmk** [citrix/terraform-provider-citrixadc#933]
# Contact us

> For any immediate issues or help , reach out to us at appmodernization@citrix.com !

# Feature Request
Please enable stting sslprofile for citrixadc_vpnvserver.

**Is your feature request related to a problem? Please describe.**
Hi Citrix. We're getting more and more into terraform for building adc entities. When trying to setup a Citrix Gateway Virtual Servers using terraform all works fine except that I'm not able to enable (bind) a sslprofile to a vpnvserver. I thought of binding the gateway vserver to a csvserver where we can use sslprofile in terraform, but as we use that csvserver also for aaa (so there's a content switching policy directing to a aaa vserver) we cannot bind a vpnvserver to that csvserver.

**Describe the solution you'd like**
For vpnvserver there's a citrixadc_sslvserver_sslcertkey_binding for binding the ssl cert to the vpnvserver. Maybe it is possible to adopt that to something like citrixadc_sslvserver_sslprofile_binding in order to setup sslprofile on vpnvserver. Or there is a way to have an attribute sslprofile in citrixadc_vpnvserver. For citrixadc_csvserver this attribute exists and works fine, but not for citrixadc_vpnvserver.

**Describe alternatives you've considered**
Using sslprofile on csvserver and binding the vpnvserver via content switching policy will not work if you already have an aaa vserver bound to the csvserver.

**Additional context**
![grafik](https://user-images.githubusercontent.com/115075777/194036989-ce6103fd-aa82-450d-be4d-eaa4d618d7a7.png)

**Comment by vadharm** [comment]
Hi @nicohoffmannhmk , 
Thanks for reaching out. I believe you are asking for new capability in NetScaler- citrixadc_sslvserver_sslprofile_binding in order to setup sslprofile on vpnvserver. 
This is beyond the scope of the Terraform provider. Please raise this as feature enhancement request with your account team. Whats your organization ? 
Best,
Mayur
