### ISSUE TITLE
Ocsp responder binding missing ?

### ISSUE THREAD

**Issue by olivierHa** [citrix/terraform-provider-citrixadc#943]
Hello, 

I am trying to use a "citrixadc_sslocspresponder" newly created, but I can't find a way to bind this OCSP responder to a "sslcertKey".

Is there a way to use it ?

I can bind it using the CLI, and terraform doesn't remove it.

What I am missing ?

Regards

Olivier

**Comment by rohit-myali** [comment]
Hello @olivierHa , Thanks for the issue.
The resource `sslcertkey_sslocspresponder_binding` is missing from the terraform. The resource is created and it will be soon released to the terraform registry.

Thanks,
Rohit

**Comment by olivierHa** [comment]
Hello Rohit, 

Thanks for your quick answer.
I will be happy to test this binding as soon as it is released and make you a feedback.

Regards
Olivier

**Comment by rohit-myali** [comment]
Hello @olivierHa ,
The resource `sslcertkey_sslocspresponder_binding` is released in the Terraform Registry
Please file the documentation link [here](https://registry.terraform.io/providers/citrix/citrixadc/latest/docs/resources/sslcertkey_sslocspresponder_binding)

Thanks,
Rohit

**Comment by olivierHa** [comment]
Nice ! Thanks a lot.
