### ISSUE TITLE
[BUG] Missing attribute ipaddress for lbmonitor ressource

### ISSUE THREAD

**Issue by olivierHa** [citrix/terraform-provider-citrixadc#952]
Hello, 

When creating a monitor using type DNS (or TCP_DNS) , using "querytype" Address for the healthcheck,  the property "ipaddress" isn't available to set the IP that is expected.

Regards

Olivier

**Comment by rohit-myali** [comment]
Hello @olivierHa,
Thanks for raising this issue.
We have fixed it in our latest release.
