### ISSUE TITLE
[FEATURE REQUEST] Botnet Profile : Settings missing from citrixadc_botprofile

### ISSUE THREAD

**Issue by kaiAsmOne** [citrix/terraform-provider-citrixadc#961]
# Contact us

> For any immediate issues or help , reach out to us at appmodernization@citrix.com !

# Feature Request
With the current implementation of citrixadc_botprofile it is not possible to set the following:

Signature Multi User-Agent Header Action
Log Signature Multi User-Agent Header Action
Signature No User-Agent Header Action
Log Signature No User-Agent Header Action

**Is your feature request related to a problem? Please describe.**
With the current botnet implementation it is not possible to produce a working configuration for most websites
due to default No User-Agent Header Action = Drop

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by rohit-myali** [comment]
Hello @kaiAsmOne ,
Thanks for raising this issue. We have added the supporting attributes to `botprofile` in out latest release 1.27.0.
Please find the link to docs [here](https://registry.terraform.io/providers/citrix/citrixadc/latest/docs/resources/botprofile)

**Comment by kaiAsmOne** [comment]
I wish you could see the things i do in Azure with the citrixadc provider in azure. 
I wish you could see how the work you guys do with focusing on the Netscaler fills a gap in the industry.

Thank you for your commitment. 

I have 3500 lines of code building best practise netscalers in azure. 3500 lines of code with citrixadc alone.

**Comment by konstantika** [comment]
Hi @kaiAsmOne, we are really happy to hear that. 
Please check you email. I've just sent you an email to discuss.
