### ISSUE TITLE
[FEATURE REQUEST] theme binding for authentication vservers

### ISSUE THREAD

**Issue by slauger** [citrix/terraform-provider-citrixadc#962]
# Feature Request

It want to manage the theme binding for a authentication vserver.

Currently there is a `vpnvserver_vpnportaltheme_binding` for VPN vServers, but something similar is missing for AAA vServers.

**Comment by rohit-myali** [comment]
Hello @slauger ,
Is it this resource `authenticationvserver_vpnportaltheme_binding` you are looking for? If so [here](https://registry.terraform.io/providers/citrix/citrixadc/latest/docs/resources/authenticationvserver_vpnportaltheme_binding) is the documentation for that..!!
Or please notify me if anything other..!!

**Comment by slauger** [comment]
Hi @rohit-myali ,

thanks for the quick response. `authenticationvserver_vpnportaltheme_binding` was exactly what i was searching for. Somehow i must overseen the resource in the documentation. Thanks!
