### ISSUE TITLE
[BUG] citrixadc_dnsnameserver does not handle correct state for remote nameservers

### ISSUE THREAD

**Issue by HS1542** [citrix/terraform-provider-citrixadc#963]
Hello,

**It seems like the provider citrixadc_dnsnameserver does not properly collect state for remote nameserver objects.**
If you configure a resource for either one nameserver of type UDP_TCP or two resources objects on of type UDP and the other TCP for the same IP, the result is the same; The Netscaler will produce 2 objects:

resource "citrixadc_dnsnameserver" "googledns-udp" {
    ip = "8.8.8.8"
    local = false
    state = "ENABLED"
    type = "UDP"
    dnsprofilename = "dns_profile_cache_disabled"
    depends_on = [
      citrixadc_dnsprofile.dns_profile_cache_disabled
    ]
}
resource "citrixadc_dnsnameserver" "googledns-tcp" {
    ip = "8.8.8.8"
    local = false
    state = "ENABLED"
    type = "TCP"
    dnsprofilename = "dns_profile_cache_disabled"
    depends_on = [
      citrixadc_dnsprofile.dns_profile_cache_disabled
    ]
}

> show dns nameServer
1)       8.8.8.8  -  State: DOWN        Protocol: UDP
        DNS profile name: dns_profile_cache_disabled
2)       8.8.8.8  -  State: DOWN        Protocol: TCP
        DNS profile name: dns_profile_cache_disabled

If you  then subsequently try to reapply the project with or without any changes, it fetches state:
citrixadc_dnsnameserver.googledns-tcp: Refreshing state... [id=8.8.8.8]
citrixadc_dnsnameserver.googledns-udp: Refreshing state... [id=8.8.8.8]

The provider will then always consider the state to have been changed, and will try to replace the configuration:
I guess this might be because it uses only the id=<ip-address> as a distinguisher?

  # citrixadc_dnsnameserver.googledns-tcp will be updated in-place
  ~ resource "citrixadc_dnsnameserver" "googledns-tcp" {
        id             = "8.8.8.8"
      ~ type           = "UDP" -> "TCP"
        # (4 unchanged attributes hidden)
    }

If you try to use the UDP_TCP type, the result when you reapply will be:

  # citrixadc_dnsnameserver.googledns-udp will be created
  + resource "citrixadc_dnsnameserver" "googledns-udp" {
      + dnsprofilename = "dns_profile_cache_disabled"
      + id             = (known after apply)
      + ip             = "8.8.8.8"
      + local          = false
      + state          = "ENABLED"
      + type           = "UDP_TCP"
    }

  # citrixadc_dnsnameserver.googledns-udp will be updated in-place
  ~ resource "citrixadc_dnsnameserver" "googledns-udp" {
        id             = "8.8.8.8"
      ~ type           = "UDP" -> "UDP_TCP"
        # (4 unchanged attributes hidden)
    }

**Comment by rohit-myali** [comment]
Hello @HS1542 ,
Thanks for raising this issue. 
We have fixed this issue in our latest Terraform release 1.27.0. Link to documentation [here](https://registry.terraform.io/providers/citrix/citrixadc/latest/docs/resources/dnsnameserver)
