### ISSUE TITLE
[BUG] Order of operation

### ISSUE THREAD

**Issue by ssdeepan** [citrix/terraform-provider-citrixadc#964]
# Contact us

> For any immediate issues or help , reach out to us at appmodernization@citrix.com !

# Bug Report

Terraform fails to  provision some resources during the terraform apply due to order of operation. All the resources can be provisioned successfully by running terraform apply several times.

**To Reproduce**
Steps to reproduce the behaviour:
1. My terraform files are
- rewrite policies and actions
- cspolicies and actions
- responder policies and actions

2. which terraform command I am getting the error
terraform apply

3. Terraform output logs / Error I am facing on the console
Error: [ERROR] nitro-go: Failed to update resource of type csvserver_cspolicy_binding,  err=failed: 404 Not Found ({ "errorcode": 2054, "message": "No such policy exists", "severity": "ERROR" })

Error: [ERROR] nitro-go: Failed to update resource of type lbvserver_rewritepolicy_binding,  err=failed: 404 Not Found ({ "errorcode": 2054, "message": "No such policy exists", "severity": "ERROR" })

Error: [ERROR] nitro-go: Failed to update resource of type lbvserver_responderpolicy_binding,  err=failed: 404 Not Found ({ "errorcode": 2054, "message": "No such policy exists", "severity": "ERROR" })

**Expected behaviour**
Provision all the resources running terraform apply only one time.

**Environment (please complete the following information):**
 - OS: Mac
 - `terraform version` output
 Terraform v1.3.1
on darwin_arm64
- Provider Version: citrixadc 1.24.0

**Comment by ssdeepan** [comment]
Hi @rohit-myali 
We have added dependency and still getting errors. 

Config:

# Responder Policies
resource "citrixadc_responderpolicy" "this" {
  for_each                        = var.responder_policies

  name                            = format("resppol-%s-%s",trimprefix(var.name, "lbvs-ssl-"), each.key)
  action                          = format("respact-%s-%s",trimprefix(var.name, "lbvs-ssl-"), each.key)
  rule                            = each.value.rule
}
resource "citrixadc_responderaction" "this" {
  for_each                        = var.responder_policies

  name                            = format("respact-%s-%s",trimprefix(var.name, "lbvs-ssl-"), each.key)
  type                            = each.value.type
  target                          = each.value.target
  htmlpage                        = each.value.htmlpage

  depends_on = [
    citrixadc_responderpolicy.this
  ]
}

Error:
Error: [ERROR] nitro-go: Failed to update resource of type lbvserver_rewritepolicy_binding,  err=failed: 404 Not Found ({ "errorcode": 2054, "message": "No such policy exists", "severity": "ERROR" })
Error: [ERROR] nitro-go: Failed to update resource of type lbvserver_responderpolicy_binding,  err=failed: 404 Not Found ({ "errorcode": 2054, "message": "No such policy exists", "severity": "ERROR" })

Error: [ERROR] nitro-go: Failed to create resource of type rewritepolicy, name=rwpol-lbvs-http-test-addpath, err=failed: 404 Not Found ({ "errorcode": 538, "message": "Action does not exist", "severity": "ERROR" })
Error: [ERROR] nitro-go: Failed to create resource of type responderpolicy, name=resppol-lbvs-http-test-io, err=failed: 404 Not Found ({ "errorcode": 538, "message": "Action does not exist", "severity": "ERROR" })

**Comment by rohit-myali** [comment]
Hello @ssdeepan ,
As I observe your terraform configuration, the dependencies are reversed. The resource `responderpolicy` depends on completion of `responderaction` or in other words, `responderpolicy` should wait until the `responderaction` is created. So there should be a `depends_on` block in `responderpolicy` and not in `responderaction`.

So, the actual configuration for the above resources will be 
```hcl

resource "citrixadc_responderpolicy" "this" {
  for_each = var.responder_policies

  name   = format("resppol-%s-%s", trimprefix(var.name, "lbvs-ssl-"), each.key)
  action = format("respact-%s-%s", trimprefix(var.name, "lbvs-ssl-"), each.key)
  rule   = each.value.rule

  depends_on = [
    citrixadc_responderaction.this
  ]
}
resource "citrixadc_responderaction" "this" {
  for_each = var.responder_policies

  name     = format("respact-%s-%s", trimprefix(var.name, "lbvs-ssl-"), each.key)
  type     = each.value.type
  target   = each.value.target
  htmlpage = each.value.htmlpage
}
```

Please try the above configuration and let me know if there is anything.!!

**Comment by rohit-myali** [comment]
Hello @ssdeepan,
Please check the above configuration that I have provided. I'm closing this issue. Please feel free to open issues if any. 

Thanks,
Rohit
