### ISSUE TITLE
[FEATURE REQUEST] Allow importing of citrixadc_policypatset, citrixadc_policypatset_pattern_binding

### ISSUE THREAD

**Issue by ksandrmatveyev** [citrix/terraform-provider-citrixadc#975]
# Contact us

> For any immediate issues or help , reach out to us at appmodernization@citrix.com !

# Feature Request

**Is your feature request related to a problem? Please describe.**
Hello. At the current moment, we are in process to move to Terraform for managing our existing Citrix ADC, which has a lot of resources that were created manually. Some of the can be [imported](https://developer.hashicorp.com/terraform/cli/import), but not the following:
- citrixadc_policypatset https://registry.terraform.io/providers/citrix/citrixadc/latest/docs/resources/policypatset
- citrixadc_policypatset_pattern_binding https://registry.terraform.io/providers/citrix/citrixadc/latest/docs/resources/policypatset_pattern_binding

As example, we are using policypetset for content switching policy: `http.req.url.path.set_text_mode(ignorecase).contains_any(patset)`

**Describe the solution you'd like**
```
terraform import citrixadc_policypatset.some id
terraform import citrixadc_policypatset_pattern_binding.some patset_id,key_name
```
Example https://registry.terraform.io/providers/citrix/citrixadc/latest/docs/resources/servicegroup_lbmonitor_binding#import

**Describe alternatives you've considered**
No alternatives for now. We have to destroy existing resources (patset and its bindings) and create new. We can't import them in any way

**Additional context**

**Comment by rohit-myali** [comment]
Hello @ksandrmatveyev ,
Very happy to hear that you are in the process to move to Terraform for managing your existing Citrix ADC. We are very much happy to help you.

We have implemented the terraform-import for the resources `citrixadc_policypatset` and `citrixadc_policypatset_pattern_binding` and it is released into terraform registry in our latest release v1.29.0.

Refer here for docs:
[`citrixadc_policypatset`](https://registry.terraform.io/providers/citrix/citrixadc/latest/docs/resources/policypatset#import)
[`citrixadc_policypatset_pattern_binding`](https://registry.terraform.io/providers/citrix/citrixadc/latest/docs/resources/policypatset_pattern_binding#import)


Thanks,
Rohit
