### ISSUE TITLE
[BUG] Cannot create a nsip

### ISSUE THREAD

**Issue by jungekim** [citrix/terraform-provider-citrixadc#981]
# Contact us

> For any immediate issues or help , reach out to us at appmodernization@citrix.com !

# Bug Report

**Describe the bug**
cannot create a nsip in a partition (not the default parition)

**To Reproduce**
Steps to reproduce the behaviour:
1. My terraform files are
 : a "live-pg-web" partition has been created and terraform plan as follows;

main.tf
resource "citrixadc_nsip" "tf_snip" {

  provider = citrixadc.web
  
  ipaddress = "10.15.16.11"
  type = "SNIP"
  netmask = "255.255.255.0"
  icmp = "ENABLED"
  state = "ENABLED"
}

2. provider.tf
provider "citrixadc" {
  alias    = "web"
  endpoint = var.mgmtDefaultSnip

  username = var.username
  password = var.password

  insecure_skip_verify = true

  do_login = true
  partition = "live-pg-web"
 }

2. which terraform command I am getting the error
[ansible@f8a82ac70a1a test-citrix-module]$ terraform plan
╷
│ Error: [ERROR] nitro-go: Failed to apply action on resource of type nspartition,  action=Switch err=failed: 599 Netscaler specific error ({ "errorcode": 278, "message": "Invalid argument [maxbandwidth]", "severity": "ERROR" })
│ 
│   with provider["registry.terraform.io/citrix/citrixadc"].web,
│   on provider.tf line 10, in provider "citrixadc":
│   10: provider "citrixadc" {
│ 
╵

**Comment by Vladislav-Pugachev** [comment]
try to use provider version 1.26.0, I also had the same error on 1.29.0 when creating tf_lbvserver in a partition (not default)

**Comment by rohit-myali** [comment]
Hello @jungekim ,
We have fixed the issue, please use the latest version of citrixadc-terraform-provider v1.32.0

Thanks,
Rohit
