### ISSUE TITLE
[FEATURE REQUEST] link ssl certKey

### ISSUE THREAD

**Issue by slauger** [citrix/terraform-provider-citrixadc#982]
I want to add a link from a certificate to a existing signing certificate. Is this currently already possible with this module? I couldn't find a matching resource for this command.

```
link ssl certKey tf_wc2023 alphassl_im
```

Thank you.

**Comment by HS1542** [comment]
Check out this: https://registry.terraform.io/providers/citrix/citrixadc/latest/docs/resources/sslcertkey#linkcertkeyname

**Comment by slauger** [comment]
Ah, i see. This explains why i didn't found any matching resource. Thank you!
