### ISSUE TITLE
[BUG] Missing field for Content Switching VServer Persistence Type

### ISSUE THREAD

**Issue by andrewhadam** [citrix/terraform-provider-citrixadc#983]
# Bug Report

**Describe the bug**
I was creating some new code for some existing infrastructure and we have a cs vserver configured in the following way:

``` add cs vserver andrewtest SSL 1.1.1.1 443 -cltTimeout 300 -downStateFlush DISABLED -tcpProfileName nstcp_default_tcp_lfp -appflowLog DISABLED -persistenceType NONE ```

When I translate that into terraform code and attempt to make a plan, I receive the following error:

``` Error: unsupported argument
...
An argument named "persistencetype" is not expected here```

**Expected behaviour**
Should have persistencetype


**Environment (please complete the following information):**
 - OS: Mac
 - TF Version - 1.3.7
 - Go Version - 1.19

**Comment by rohit-myali** [comment]
Hey @andrewhadam ,
Thanks for bringing this to us. I did add `persistencetype` to the list of attributes of csvserver. It will be released to the terraform registry in our next release and I will update you on the next release.

**Comment by rohit-myali** [comment]
Hey @andrewhadam ,
We have released the latest providers to the terraform registry v1.31.0.
Link to the docs of `citrixadc_csvserver`: https://registry.terraform.io/providers/citrix/citrixadc/latest/docs/resources/csvserver#persistencetype

**Comment by andrewhadam** [comment]
Thanks @rohit-myali!  Look forward to using it as soon as I'm able to update to the latest version of the provider!

**Comment by rohit-myali** [comment]
Great @andrewhadam !!!
