### ISSUE TITLE
[BUG] Plugin crashes upgrading from 1.26.0 -> 1.27.0

### ISSUE THREAD

**Issue by andrewhadam** [citrix/terraform-provider-citrixadc#984]
# Bug Report

**Describe the bug**
We have a pipeline that heavily utilizes the citrixadc plugin.  When I went to upgrade the plugin version from 1.23.0 to 1.29.0, the plugin started crashing.  I started to trace back when exactly the plugin crashing starts to occur and it happens going from 1.26.0 to 1.27.0.  This will hard block us from being able to upgrade the plugin further until this can be addressed.

**To Reproduce**
Steps to reproduce the behaviour:
1. My terraform files are
```hcl
resource "citrixadc_systemuser" "make_rouser_user" {
  username = "rouser"
  password = var.rouser_pw
  timeout  = 900

  cmdpolicybinding {
    policyname = "read-only"
    priority   = 100
  }
}
...
```

If you require more details from the file, let me know and we can discuss but that's the block from the first error shown in section 3.  

2. which terraform command I am getting the error
terraform plan

3. Terraform output logs

```
╷
│ Error: Plugin did not respond
│
│   with citrixadc_systemuser.make_rouser_user,
│   on main.tf line 18, in resource "citrixadc_systemuser" "make_rouser_user":
│   18: resource "citrixadc_systemuser" "make_rouser_user" {
│
│ The plugin encountered an error, and failed to respond to the
│ plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more
│ details.
╵
╷
│ Error: Request cancelled
│
│   with citrixadc_systemcmdpolicy.create_all_systemcmdpolicy["geoip_cmd_policy"],
│   on main.tf line 92, in resource "citrixadc_systemcmdpolicy" "create_all_systemcmdpolicy":
│   92: resource "citrixadc_systemcmdpolicy" "create_all_systemcmdpolicy" {
│
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.
```

4. Error I am facing on the console

```Stack trace from the terraform-provider-citrixadc_v1.27.0 plugin:

panic: runtime error: index out of range [1] with length 1

goroutine 129 [running]:
github.com/citrix/terraform-provider-citrixadc/citrixadc.readDnsnameserverFunc(0xc0009324d0, {0x1e76600?, 0xc000424e80})
	github.com/citrix/terraform-provider-citrixadc/citrixadc/resource_citrixadc_dnsnameserver.go:121 +0x794
github.com/hashicorp/terraform/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000337800, 0xc000a6a640, {0x1e76600, 0xc000424e80})
	github.com/hashicorp/terraform@v0.12.20/helper/schema/resource.go:455 +0x1aa
github.com/hashicorp/terraform/helper/plugin.(*GRPCProviderServer).ReadResource(0xc00000ef50, {0xc000a6a190?, 0x11a08a6?}, 0xc000a6a190)
	github.com/hashicorp/terraform@v0.12.20/helper/plugin/grpc_provider.go:525 +0x34b
github.com/hashicorp/terraform/internal/tfplugin5._Provider_ReadResource_Handler({0x1fed3e0?, 0xc00000ef50}, {0x239f2a0, 0xc00082ffb0}, 0xc00078c360, 0x0)
	github.com/hashicorp/terraform@v0.12.20/internal/tfplugin5/tfplugin5.pb.go:3153 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0001b0780, {0x23a2e08, 0xc0001b0900}, 0xc000742100, 0xc00078f530, 0x2ac7ff0, 0x0)
	google.golang.org/grpc@v1.27.0/server.go:1024 +0xd1e
google.golang.org/grpc.(*Server).handleStream(0xc0001b0780, {0x23a2e08, 0xc0001b0900}, 0xc000742100, 0x0)
	google.golang.org/grpc@v1.27.0/server.go:1313 +0xa05
google.golang.org/grpc.(*Server).serveStreams.func1.1()
	google.golang.org/grpc@v1.27.0/server.go:722 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.27.0/server.go:720 +0xea

Error: The terraform-provider-citrixadc_v1.27.0 plugin crashed!
```

**Expected behaviour**
Provide a plan

**Environment (please complete the following information):**
 - Broken both on Mac OSX and pipeline which is Linux
 - TF Version - 1.3.7
 - Go: 1.19

**Comment by kaiAsmOne** [comment]
Hi, 

I am experiencing similar issues with the GRPCProvider



│ Error: Request cancelled
│ 
│   with citrixadc_vlan_interface_binding.systemNetworkConfigVLAN_FE,
│   on main.tf line 149, in resource "citrixadc_vlan_interface_binding" "systemNetworkConfigVLAN_FE":
│  149: resource "citrixadc_vlan_interface_binding" "systemNetworkConfigVLAN_FE" {
│ 
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Request cancelled
│ 
│   with citrixadc_vlan_interface_binding.systemNetworkConfigVLAN_BE,
│   on main.tf line 155, in resource "citrixadc_vlan_interface_binding" "systemNetworkConfigVLAN_BE":
│  155: resource "citrixadc_vlan_interface_binding" "systemNetworkConfigVLAN_BE" {
│ 
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.
╵
╷
│ Error: Request cancelled

**Comment by andrewhadam** [comment]
This might be a good hint actually.  We had just started to upgrade a number of our hosts from 13.0 to 13.1 so this might coincide with those upgrades as well.

**Comment by rohit-myali** [comment]
Hey @andrewhadam, 
Do you see the error when you Upgrade your NetScaler(ADC's) or when you upgrade the terraform provider citrixadc version ?

**Comment by rohit-myali** [comment]
Hey @andrewhadam ,
Yes, the id of the resource has changed. We found it was the bug before so we did fix it. So, it is advised to use it according to the latest updates.

Thanks
Rohit

**Comment by rohit-myali** [comment]
Hello @andrewhadam ,
Sorry for the inconvenience caused due to the change of id of the resource. I made the resource backward compatible. 
You can use the latest citrixadc terraform provider version v1.34.0.

Thank You
Rohit

**Comment by kaiAsmOne** [comment]
Thank you for this update. All my Netscalers are now again fully terraform managed 🥇
