### ISSUE TITLE
[BUG] Newer 13.1 Builds causes plugin.(*GRPCProvider).ReadResource: error="rpc error: code = Canceled desc = context canceled"

### ISSUE THREAD

**Issue by kaiAsmOne** [citrix/terraform-provider-citrixadc#990]
There seems to be an issue using the Netscaler Terraform Provider with Newer 13.1 Builds

After applying fixes for the CVE´s reported before christmas i have upgraded to latest 13.1 build  (13.1 37.38)
When i do a terraform plan on upgraded Netscalers

i get the below error on random lines in my script (The error occurs on random terraform code)

│ Error: Request cancelled
│ 
│   with citrixadc_server.adcshared,
│   on main.tf line 185, in resource "citrixadc_server" "adcshared":
│  185: resource "citrixadc_server" "adcshared" {
│ 
│ The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.

When i enable Terraform Logging (export TF_LOG="WARN" )
I can see the following errors in my terraform log file:

 [ERROR] plugin.(*GRPCProvider).ReadResource: error="rpc error: code = Canceled desc = context canceled"
[ERROR] plugin.(*GRPCProvider).ReadResource: error="rpc error: code = Unavailable desc = error reading from server: EOF"
[ERROR] plugin.(*GRPCProvider).ReadResource: error="rpc error: code = Canceled desc = context canceled"
[ERROR] plugin.(*GRPCProvider).ReadResource: error="rpc error: code = Unavailable desc = error reading from server: EOF"

**To Reproduce**
Steps to reproduce the behaviour:
1. My terraform files are
```hcl
# my terraform script here
```
2. which terraform command I am getting the error
3. Terraform output logs
4. Error I am facing on the console

**Expected behaviour**

**Screenshots**

**Environment (please complete the following information):**
 - OS: Mac
 - TF Version: 1.3.4
 - `go version: 1.17

**Additional context**

**Comment by kaiAsmOne** [comment]
I have verified that latest 13.0 build works fine.

**Comment by rohit-myali** [comment]
Hey @kaiAsmOne , Thanks for contacting us..!!
Can you please specify which resource caused this error, so that we can reproduce the issue and fix it!!

**Comment by kaiAsmOne** [comment]
Hi, 

This happens on random resources on each run.
i.e it happens on

citrixadc_server
citrixadc_lbmonitor
citrixadc_servicegroup
citrixadc_dnsnameserver

**Comment by kaiAsmOne** [comment]
This can be closed. Issue resolved in 1.34.0
