### ISSUE TITLE
Error: [ERROR] FindResrouceArrayWithParams: non zero errorcode 344

### ISSUE THREAD

**Issue by jparri1** [citrix/terraform-provider-citrixadc#991]
I'm not sure if this is best place to put this, but I'm receiving Error: [ERROR] FindResourceArrayWithParams: non zero errorcode 344. I cant tell which resource this refers to and also not sure if I just need to clear out my state file to resolve this. v1.29.0/v1.30.0

**Comment by rohit-myali** [comment]
Hello @jparri1 ,
Thanks for reaching out to us..!!
I need more info in order to resolve this issue.
Can you provide your config(if possible) else please mention the resource type for which you are facing this error.

Thanks,
Rohit
