### ISSUE TITLE
[BUG] citrixadc_hanode - hastatus does not handle state "UP"

### ISSUE THREAD

**Issue by HS1542** [citrix/terraform-provider-citrixadc#996]
# Bug Report

**Describe the bug**
Subsequently running a Terraform project where you have defined the citrixadc_hanode, hastatus to "ENABLED", the provider will gather information that the state is "UP" and hence will apply the hastatus every time the project is run.

**To Reproduce**
```
# citrixadc_hanode.HAmode will be updated in-place
~ resource "citrixadc_hanode" "HAmode" {
      ~ hastatus                      = "UP" -> "ENABLED"
          id                                = "0"
          # (8 unchanged attriutes hidden)
    }
```

**Comment by rohit-myali** [comment]
Hey @HS1542, 
Thank you for reaching us.!!!
The supported values for `hastatus` attributes are listed below Please refer below Image

![image](https://user-images.githubusercontent.com/88589975/218016349-b22145c4-343a-41c0-8fae-7f7ca8895617.png)

Thank You,
Rohit

**Comment by HS1542** [comment]
Hello Rohit,

That is correct, possible WRITE values are: ENABLED, STAYSECONDARY, DISABLED or STAYPRIMARY.
However, as shown by the logs, the provider reads out "UP" as the state, so I can just assume that the provider fetches the hacurstate instead of the hastate from the Nitro API?

I still consider this a bug and would kindly ask you to review it.

![hastate](https://user-images.githubusercontent.com/118446780/218036664-c0b93dd4-9b81-4f99-8359-485ac6c8010f.PNG)

**Comment by rohit-myali** [comment]
Hi @HS1542 ,
Thank you for reaching us.!!!
I have fixed the issue you were facing. We will be releasing it to the Terraform Registry soon. I will update you on that.
Please feel free to raise any issue you face.

Thanks,
Rohit

**Comment by rohit-myali** [comment]
Hi @HS1542 
Thank you for reaching us.!!!
I have fixed the issue you were facing. We have released to the terraform registry.
Please use the latest terraform provider version [v1.34.0](https://registry.terraform.io/providers/citrix/citrixadc/latest/docs/resources/hanode).

Thanks
ROhit

**Comment by HS1542** [comment]
Hello,

I can confirm that you have fixed this, thank you!
