### ISSUE TITLE
[FEATURE REQUEST] citrixadc_systemgroup - implementation of allowedmanagementinterface attribute?

### ISSUE THREAD

**Issue by HS1542** [citrix/terraform-provider-citrixadc#998]
# [FEATURE REQUEST] citrixadc_systemgroup - implementation of allowedmanagementinterface attribute?
As far as I can see, the allowedmanagementinterface attribute as referenced here:
https://developer-docs.citrix.com/projects/citrix-adc-nitro-api-reference/en/latest/configuration/system/systemgroup/
is not supported by the terraform provider, resulting in the default "NS_INTERFACE_ALL"/"CLI, API" value  and not configurable:
https://registry.terraform.io/providers/citrix/citrixadc/latest/docs/resources/systemgroup

I kindly request for you to include the allowedmanagementinterface attribute in citrixadc_systemgroup.

**Comment by rohit-myali** [comment]
Hey @HS1542 ,
Thanks you for bringing this up!!
I have added attribute `allowedmanagementinterface` to the resource `citrixadc_systemgroup`. Please download the latest v1.32.0 terraform provider version to configure NetScalers. Link to the docs: https://registry.terraform.io/providers/citrix/citrixadc/latest/docs/resources/systemgroup#allowedmanagementinterface
