### ISSUE TITLE
[BUG] SNMP Community Permissions Field Optional or Required?

### ISSUE THREAD

**Issue by andrewhadam** [citrix/terraform-provider-citrixadc#999]
**Describe the bug**
This is either a bug or documentation errors but if I create an snmpcommunity object, https://github.com/citrix/terraform-provider-citrixadc/blob/master/docs/resources/snmpcommunity.md suggests the permissions field is optional but if I try and create the object, the provider errors and says it is a required field.  Either documentation should be updated to indicate its required or the provider should not require it if it isn't required.

**To Reproduce**
Steps to reproduce the behaviour:

Build any snmcommunity object w/ only communityname specified.

**Environment (please complete the following information):**
Plugin Version 1.26.0

**Comment by rohit-myali** [comment]
Hello @andrewhadam 
Thank you for contacting us.

We have updated the resource and documentation for the [`citrixadc_snmpcommunity`](https://registry.terraform.io/providers/citrix/citrixadc/latest/docs/resources/snmpcommunity).
Please use our latest terraform provider [v1.36.0](https://registry.terraform.io/providers/citrix/citrixadc/latest/docs/resources/snmpcommunity)
